#
# Copyright (c) 2015 Allwinnertech, Inc.
# Tyle <tyle at allwinnertech.com>
#
#

mydir = de/lowlevel_sun50iw1

obj_low = $(mydir)/de_fcc.o $(mydir)/de_gsu.o $(mydir)/de_hal.o $(mydir)/disp_al.o \
					$(mydir)/de_peak.o $(mydir)/de_rtmx.o $(mydir)/de_scaler_table.o\
					$(mydir)/de_vep_table.o $(mydir)/de_vsu.o $(mydir)/de_feat.o \
					$(mydir)/de_lcd.o $(mydir)/de_lti.o $(mydir)/de_fce.o \
					$(mydir)/de_ase.o $(mydir)/de_enhance.o \
					$(mydir)/de_smbl.o $(mydir)/de_ccsc.o $(mydir)/de_dcsc.o \
					$(mydir)/de_wb.o $(mydir)/de_dsi.o $(mydir)/de_clock.o
