# SPDX-License-Identifier: GPL-2.0

# Common objects
ccu-sunxi-ng-y					+= ccu_common.o
ccu-sunxi-ng-y					+= ccu_mmc_timing.o
ccu-sunxi-ng-y					+= ccu_reset.o

# Base clock types
ccu-sunxi-ng-y					+= ccu_div.o
ccu-sunxi-ng-y					+= ccu_frac.o
ccu-sunxi-ng-y					+= ccu_gate.o
ccu-sunxi-ng-y					+= ccu_mux.o
ccu-sunxi-ng-y					+= ccu_mult.o
ccu-sunxi-ng-y					+= ccu_phase.o
ccu-sunxi-ng-y					+= ccu_sdm.o

# Multi-factor clocks
ccu-sunxi-ng-y					+= ccu_nk.o
ccu-sunxi-ng-y					+= ccu_nkm.o
ccu-sunxi-ng-y					+= ccu_nkmp.o
ccu-sunxi-ng-y					+= ccu_nm.o
ccu-sunxi-ng-y					+= ccu_mp.o

obj-$(CONFIG_SUNXI_CCU)				+= ccu-sunxi-ng.o
obj-$(CONFIG_SUNXI_RTC_CCU)			+= rtc-sunxi-ccu.o

# SoC support
obj-$(CONFIG_SUN50IW10_CCU)	+= ccu-sun50iw10.o
obj-$(CONFIG_SUN50IW10_R_CCU)	+= ccu-sun50iw10-r.o
obj-$(CONFIG_SUN50IW10_DDR_CCU)	+= ccu-sun50iw10-ddr.o
obj-$(CONFIG_SUN50IW9_CCU)	+= ccu-sun50iw9.o
obj-$(CONFIG_SUN50IW9_R_CCU)	+= ccu-sun50iw9-r.o
obj-$(CONFIG_SUN50IW9_CCU)	+= ccu-sun50iw9-rtc.o
obj-$(CONFIG_SUNIV_F1C100S_CCU)	+= ccu-suniv-f1c100s.o
obj-$(CONFIG_SUN50I_A64_CCU)	+= ccu-sun50i-a64.o
obj-$(CONFIG_SUN50I_A100_CCU)	+= ccu-sun50i-a100.o
obj-$(CONFIG_SUN50I_A100_R_CCU)	+= ccu-sun50i-a100-r.o
obj-$(CONFIG_SUN50I_H6_CCU)	+= ccu-sun50i-h6.o
obj-$(CONFIG_SUN50I_H6_R_CCU)	+= ccu-sun50i-h6-r.o
obj-$(CONFIG_SUN4I_A10_CCU)	+= ccu-sun4i-a10.o
obj-$(CONFIG_SUN5I_CCU)		+= ccu-sun5i.o
obj-$(CONFIG_SUN6I_A31_CCU)	+= ccu-sun6i-a31.o
obj-$(CONFIG_SUN8I_A23_CCU)	+= ccu-sun8i-a23.o
obj-$(CONFIG_SUN8I_A33_CCU)	+= ccu-sun8i-a33.o
obj-$(CONFIG_SUN8I_A83T_CCU)	+= ccu-sun8i-a83t.o
obj-$(CONFIG_SUN8I_H3_CCU)	+= ccu-sun8i-h3.o
obj-$(CONFIG_SUN8I_V3S_CCU)	+= ccu-sun8i-v3s.o
obj-$(CONFIG_SUN8I_DE2_CCU)	+= ccu-sun8i-de2.o
obj-$(CONFIG_SUN8I_R_CCU)	+= ccu-sun8i-r.o
obj-$(CONFIG_SUN8I_R40_CCU)	+= ccu-sun8i-r40.o
obj-$(CONFIG_SUN9I_A80_CCU)	+= ccu-sun9i-a80.o
obj-$(CONFIG_SUN9I_A80_CCU)	+= ccu-sun9i-a80-de.o
obj-$(CONFIG_SUN9I_A80_CCU)	+= ccu-sun9i-a80-usb.o
