# SPDX-License-Identifier: GPL-2.0
#
# Ky Clock specific Makefile
#

#SoC support
obj-$(CONFIG_KY_X1_CCU)     += ccu-ky-x1.o ccu_mix.o ccu_pll.o ccu_dpll.o ccu_ddn.o ccu_ddr.o
obj-$(CONFIG_KY_X1PRO_CCU)   += ccu-ky-x1pro.o
