# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_AW_GPU_PM_DOMAINS) += gpu_domain.o
obj-$(CONFIG_AW_PM_DOMAINS) += pm_domains.o
obj-$(CONFIG_AW_PCK600_DOMAINS) += pck600_domains.o
obj-$(CONFIG_AW_POWER_DOMAIN_TEST) += sunxi_pd_test.o
ccflags-y := -DDYNAMIC_DEBUG_MODULE
