obj-$(CONFIG_CSI_VIN)           += actuator.o

obj-$(CONFIG_ACTUATOR)   += ad5820_act.o
obj-$(CONFIG_ACTUATOR)   += dw9714_act.o
obj-$(CONFIG_ACTUATOR)   += ov8825_act.o
obj-$(CONFIG_ACTUATOR)   += an41908a_act.o

