obj-$(CONFIG_DISP2_SUNXI) += disp.o

disp-objs :=  dev_disp.o dev_fb.o dev_disp_debugfs.o
disp-objs	+= disp_sys_intf.o dev_composer.o
disp-objs	+= de/disp_display.o de/disp_features.o de/disp_device.o de/disp_lcd.o de/disp_manager.o de/disp_private.o \
							de/disp_smart_backlight.o de/disp_enhance.o de/disp_capture.o de/disp_hdmi.o de/disp_tv.o de/disp_vdevice.o
disp-objs += lcd/panels.o lcd/lcd_source.o lcd/default_panel.o lcd/lt070me05000.o lcd/wtq05027d01.o lcd/t27p06.o lcd/st7789s.o
disp-$(CONFIG_ARCH_SUN8IW6) += de/lowlevel_sun8iw6/de_fcc.o de/lowlevel_sun8iw6/de_gsu.o de/lowlevel_sun8iw6/de_hal.o de/lowlevel_sun8iw6/disp_al.o \
						de/lowlevel_sun8iw6/de_peak.o de/lowlevel_sun8iw6/de_rtmx.o de/lowlevel_sun8iw6/de_scaler_table.o\
						de/lowlevel_sun8iw6/de_vep_table.o de/lowlevel_sun8iw6/de_vsu.o de/lowlevel_sun8iw6/de_feat.o \
						de/lowlevel_sun8iw6/de_lcd.o de/lowlevel_sun8iw6/de_lti.o de/lowlevel_sun8iw6/de_fce.o \
						de/lowlevel_sun8iw6/de_ase.o de/lowlevel_sun8iw6/de_enhance.o \
						de/lowlevel_sun8iw6/de_smbl.o de/lowlevel_sun8iw6/de_ccsc.o de/lowlevel_sun8iw6/de_dcsc.o \
						de/lowlevel_sun8iw6/de_wb.o de/lowlevel_sun8iw6/de_dsi.o de/lowlevel_sun8iw6/de_clock.o
disp-$(CONFIG_ARCH_SUN8IW7) += de/lowlevel_sun8iw7/de_fcc.o de/lowlevel_sun8iw7/de_gsu.o de/lowlevel_sun8iw7/de_hal.o de/lowlevel_sun8iw7/disp_al.o \
						de/lowlevel_sun8iw7/de_peak.o de/lowlevel_sun8iw7/de_rtmx.o de/lowlevel_sun8iw7/de_scaler_table.o\
						de/lowlevel_sun8iw7/de_vep_table.o de/lowlevel_sun8iw7/de_vsu.o de/lowlevel_sun8iw7/de_feat.o \
						de/lowlevel_sun8iw7/de_lcd.o de/lowlevel_sun8iw7/de_lti.o de/lowlevel_sun8iw7/de_fce.o \
						de/lowlevel_sun8iw7/de_ase.o de/lowlevel_sun8iw7/de_enhance.o \
						de/lowlevel_sun8iw7/de_smbl.o de/lowlevel_sun8iw7/de_ccsc.o de/lowlevel_sun8iw7/de_dcsc.o \
						de/lowlevel_sun8iw7/de_wb.o de/lowlevel_sun8iw7/de_clock.o
disp-$(CONFIG_ARCH_SUN8IW8) += de/lowlevel_sun8iw8/de_fcc.o de/lowlevel_sun8iw8/de_gsu.o de/lowlevel_sun8iw8/de_hal.o de/lowlevel_sun8iw8/disp_al.o \
						de/lowlevel_sun8iw8/de_peak.o de/lowlevel_sun8iw8/de_rtmx.o de/lowlevel_sun8iw8/de_scaler_table.o\
						de/lowlevel_sun8iw8/de_vep_table.o de/lowlevel_sun8iw8/de_vsu.o de/lowlevel_sun8iw8/de_feat.o \
						de/lowlevel_sun8iw8/de_lcd.o de/lowlevel_sun8iw8/de_lti.o de/lowlevel_sun8iw8/de_fce.o \
						de/lowlevel_sun8iw8/de_ase.o de/lowlevel_sun8iw8/de_bws.o de/lowlevel_sun8iw8/de_enhance.o \
						de/lowlevel_sun8iw8/de_smbl.o de/lowlevel_sun8iw8/de_ccsc.o de/lowlevel_sun8iw8/de_dcsc.o \
						de/lowlevel_sun8iw8/de_wb.o de/lowlevel_sun8iw8/de_clock.o
disp-$(CONFIG_ARCH_SUN8IW9) += de/lowlevel_sun8iw9/de_fcc.o de/lowlevel_sun8iw9/de_gsu.o de/lowlevel_sun8iw9/de_hal.o de/lowlevel_sun8iw9/disp_al.o \
						de/lowlevel_sun8iw9/de_peak.o de/lowlevel_sun8iw9/de_rtmx.o de/lowlevel_sun8iw9/de_scaler_table.o\
						de/lowlevel_sun8iw9/de_vep_table.o de/lowlevel_sun8iw9/de_vsu.o de/lowlevel_sun8iw9/de_feat.o \
						de/lowlevel_sun8iw9/de_lcd.o de/lowlevel_sun8iw9/de_lti.o de/lowlevel_sun8iw9/de_fce.o \
						de/lowlevel_sun8iw9/de_ase.o de/lowlevel_sun8iw9/de_bws.o de/lowlevel_sun8iw9/de_enhance.o \
						de/lowlevel_sun8iw9/de_smbl.o de/lowlevel_sun8iw9/de_ccsc.o de/lowlevel_sun8iw9/de_dcsc.o \
						de/lowlevel_sun8iw9/de_wb.o de/lowlevel_sun8iw9/de_clock.o
