# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_CIX) += sky1-evb.dtb
dtb-$(CONFIG_ARCH_CIX) += sky1-evb-iso.dtb
dtb-$(CONFIG_ARCH_CIX) += sky1-orangepi-6-plus.dtb
dtb-$(CONFIG_ARCH_CIX) += sky1-orangepi-6-plus-40pin.dtb
dtb-$(CONFIG_ARCH_CIX) += sky1-orangepi-6-plus-40pin-pwm.dtb
