obj-$(CONFIG_SUNXI_THERMAL) +=  sunxi_ths_combine.o
obj-$(CONFIG_SUN50IW1P1_THERMAL) += sun50i_ths.o
obj-$(CONFIG_SUN8IW10P1_THERMAL) += sun8iw10_ths.o
obj-$(CONFIG_SUN8IW11P1_THERMAL) += sun8iw11_ths.o
obj-$(CONFIG_SUN50IW2P1_THERMAL) += sun50iw2_ths.o
