# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the PM core exception drivers.
#

obj-$(CONFIG_PM_EXCEPTION_DRIVER)				+= pm_exception_drv.o
obj-$(CONFIG_PM_EXCEPTION_PROTOCOL)				+= pm_exception_protocol.o
obj-$(CONFIG_PM_EXCP_DSM_DRIVER)				+= pm_exception_dsm.o
obj-$(CONFIG_CIX_EC_EXCEPTION_DRIVER)			+= pm_exception_ec_drv.o
