# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_CIX_EC)	+= cix_ec_kb_backlight.o
obj-$(CONFIG_CIX_EC)	+= cix_ec_lid.o
obj-$(CONFIG_CIX_EC)	+= cix_ec_light.o
obj-$(CONFIG_CIX_EC)	+= cix_ec_battery.o
obj-$(CONFIG_CIX_EC)	+= cix_ec_gpio.o
obj-$(CONFIG_CIX_EC)	+= cix_ec_charge.o
obj-$(CONFIG_CIX_EC)	+= cix_ec_pwrkey.o
obj-$(CONFIG_CIX_EC)	+= cix_ec_fan.o
obj-$(CONFIG_CIX_EC)	+= cix_ec_audio_sleeve.o
