# SPDX-License-Identifier: GPL-2.0

obj-y += rdr_platform_ap_adapter.o rdr_platform_ap_exception_logsave.o
obj-y += rdr_platform_ap_subtype.o
obj-y += rdr_platform_ap_ringbuffer.o rdr_platform_ap_hook.o
obj-y += rdr_platform_ap_cleartext.o