# SPDX-License-Identifier: GPL-2.0

subdir-ccflags-y += -I$(srctree)/kernel/
obj-y += rdr_ap_adapter.o
obj-y += rdr_ap_ringbuffer.o rdr_ap_hook.o rdr_ap_regdump.o rdr_ap_moddump.o \
		rdr_ap_exception.o rdr_ap_pstore.o rdr_ap_stack.o rdr_ap_suspend.o
