#
# softwinner 3G module driver.
#

obj-$(CONFIG_SW_3G_MODULE)	+= driver.o core.o
obj-$(CONFIG_HUAWEI_MU509)	+= mu509.o
obj-$(CONFIG_YUGA_CWM600)	+= cwm600.o
obj-$(CONFIG_OVIPHONE_EM55)	+= em55.o
obj-$(CONFIG_OVIPHONE_EM56_EM66)+= em66.o
obj-$(CONFIG_SPREADWIN_G3)	+= g3.o
obj-$(CONFIG_LONGCHEER_WM5608)	+= wm5608.o
obj-$(CONFIG_USI_MT6276MA)	+= usi6276.o
