# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the car_reverse drivers for amp.
#

obj-$(CONFIG_VIDEO_SUNXI_CAR_REVERSE_AMP) = sunxi_car_reverse.o

sunxi_car_reverse-y = car_reverse.o

ccflags-y := -DDYNAMIC_DEBUG_MODULE
