ky-dummycodec-objs := ky-dummy-codec.o
ky-hdmiaudio-objs := ky-snd-sspa.o
ky-i2s-objs := ky-snd-i2s.o
ky-pcm-objs := ky-snd-pcm-dma.o
ky-card-objs := ky-snd-card.o

obj-$(CONFIG_KY_DUMMYCODEC) += ky-dummycodec.o

obj-$(CONFIG_KY_HDMIAUDIO) += ky-hdmiaudio.o

obj-$(CONFIG_KY_I2S) += ky-i2s.o

obj-$(CONFIG_KY_PCM) += ky-pcm.o

obj-$(CONFIG_KY_CARD) += ky-card.o


