# SPDX-License-Identifier: GPL-2.0-or-later
obj-$(CONFIG_AW_HDMI_FPGA_INNOPHY_DISP2)  += hdmi_phy46.o
obj-$(CONFIG_AW_HDMI_FPGA_INNOPHY_DISP2)  += hdmi_phy56.o

hdmi_phy46-y := hdmi-inno-phy46.o
hdmi_phy56-y := hdmi-inno-phy56.o
