# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the cix dst drivers.
#

obj-y += rdr_utils.o rdr_core.o rdr_common.o rdr_field_core.o rdr_exception_core.o rdr_module_core.o rdr_dump_core.o rdr_logmonitor_core.o rdr_cleartext.o rdr_exception_trace.o
obj-$(CONFIG_PLAT_AP_HOOK) += platform_ap/
obj-$(CONFIG_PLAT_BBOX_TEST) += rdr_exception_test.o
