ccflags-y += -I$(srctree)/drivers/misc/cix/sensor/scp/include
ccflags-y += -I$(srctree)/drivers/misc/cix/cix_sensorhub/scp/

obj-$(CONFIG_CIX_SF_SCP_SUPPORT) += scp.o
scp-$(CONFIG_CIX_SF_SCP_SUPPORT) += scp_helper.o
