# Makefile for the Linux vdpo driver
# 14 Feb 2017, zhengxiaobin, <mailto:zhengxiaobin@allwinnertech.com>
#
obj-$(CONFIG_VDPO_DISP2_SUNXI) += vdpo.o
vdpo-y := drv_vdpo.o drv_vdpo_lowlevel.o drv_vdpo_timing.o
