override PVRSRV_DIR := services
override PVRSRV_FORCE_HWPERF_TO_SCHED_CLK := 1
override HOST_PRIMARY_ARCH := host_x86_64
override HOST_32BIT_ARCH := host_i386
override HOST_FORCE_32BIT := -m32
override HOST_ALL_ARCH := host_x86_64 host_i386
override TARGET_PRIMARY_ARCH := target_riscv64
override TARGET_SECONDARY_ARCH :=
override TARGET_ALL_ARCH := target_riscv64
override TARGET_FORCE_32BIT :=
override PVR_ARCH := rogue
override METAG_VERSION_NEEDED := 2.8.1.0.3
override MIPS_VERSION_NEEDED := 2014.07-1
override RISCV_VERSION_NEEDED := 1.7.1
override KERNELDIR := /home/likaiyang/work/Jindie/out/bootable/fpga/linux
override KERNEL_ID := 6.1.15-00003-g57b93bb899b2-dirty
override PVRSRV_MODULE_BASEDIR := /lib/modules/6.1.15-00003-g57b93bb899b2-dirty/extra/
override KERNEL_COMPONENTS := srvkm
override KERNEL_CROSS_COMPILE := riscv64-unknown-linux-gnu-
override WINDOW_SYSTEM := wayland
override PVRSRV_MODNAME := pvrsrvkm
override PVR_BUILD_DIR := ky
override PVR_BUILD_TYPE := release
override SUPPORT_RGX := 1
override PVR_SYSTEM := ky
override PVR_LOADER :=
override BUILD := release
override SORT_BRIDGE_STRUCTS := 1
override DEBUGLINK := 1
override RGX_BNC := 36.V.52.182
override PVRSRV_TRACE_ROGUE_EVENTS := 1
override SUPPORT_PHYSMEM_TEST := 1
override SUPPORT_MIPS_64K_PAGE_SIZE :=
override RGX_NUM_DRIVERS_SUPPORTED := 1
override RGX_FW_HEAP_OSID_ASSIGNMENT := RGX_FW_HEAP_USES_FIRMWARE_OSID
override VMM_TYPE := stub
override SUPPORT_POWMON_COMPONENT := 1
override RGX_TIMECORR_CLOCK := sched
override PDVFS_COM_HOST := 1
override PDVFS_COM_AP := 2
override PDVFS_COM_PMC := 3
override PDVFS_COM_SYSREG := 5
override PDVFS_COM_IMG_CLKDIV := 4
override PDVFS_COM := PDVFS_COM_HOST
override PVR_GPIO_MODE_GENERAL := 1
override PVR_GPIO_MODE_POWMON_PIN := 2
override PVR_GPIO_MODE := PVR_GPIO_MODE_GENERAL
override PVR_HANDLE_BACKEND := idr
override SUPPORT_DMABUF_BRIDGE := 1
override SUPPORT_USC_BREAKPOINT := 1
override SUPPORT_DI_BRG_IMPL := 1
override SUPPORT_WRAP_EXTMEM := 1
override SUPPORT_NATIVE_FENCE_SYNC := 1
override SUPPORT_DMA_FENCE := 1
override SUPPORT_FW_CORE_CLK_RATE_CHANGE_NOTIFY := 1
override SUPPORT_BUFFER_SYNC := 1
