#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FT5X16_TS)       += ft5x16_ts.o
ft5x16_ts-objs := ftxxxx_config.o ini.o ft5x.o

