# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_TYPEC_MUX_PS8743)		+= ps8743.o
obj-$(CONFIG_TYPEC_MUX_FSA4480)		+= fsa4480.o
obj-$(CONFIG_TYPEC_MUX_GPIO_GMA340)	+= gpio-gma340-mux.o
obj-$(CONFIG_TYPEC_MUX_SUNXI_PHY_SWITCHER)	+= sunxi-phy-switcher.o
