# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the touchscreen drivers.
#
# Each configuration option enables a list of files.

obj-$(CONFIG_AW_INPUT_CTP)    += gt9xx_secondary/
obj-$(CONFIG_AW_INPUT_CTP)    += gslx680new/
obj-$(CONFIG_AW_INPUT_CTP)    += wacom_pen/
obj-$(CONFIG_AW_INPUT_CTP)    += gt9xxnew/
obj-$(CONFIG_AW_INPUT_CTP)    += gt9xx/
obj-$(CONFIG_AW_INPUT_CTP)    += hynitron/
obj-$(CONFIG_AW_INPUT_CTP)    += ilitek_tddi/
obj-$(CONFIG_AW_INPUT_CTP)    += focaltech_touch/
obj-$(CONFIG_AW_INPUT_CTP)    += tlsc6x/
obj-$(CONFIG_AW_INPUT_CTP)    += gt82x/
obj-$(CONFIG_AW_INPUT_CTP)    += nvt36xxx/
