
subdir-ccflags-y += -I$(srctree)/kernel/
subdir-ccflags-y += -I$(srctree)/drivers/soc/cix/sched/
obj-$(CONFIG_CIX_CORE_CTL) += cix_core_ctl.o
cix_core_ctl-y += core_ctl/sched_avg.o
cix_core_ctl-y += core_ctl/core_ctl.o
cix_core_ctl-y += core_ctl/core_pause.o
