# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_AW_DRM_PHY) += sunxi_drm_phy.o
sunxi_drm_phy-$(CONFIG_AW_DRM_DSI_COMBOPHY) += sunxi_dsi_combophy.o

#ifeq ($(CONFIG_ARCH_SUN55IW3P1),y)
sunxi_drm_phy-$(CONFIG_AW_DRM_DSI_COMBOPHY) += sunxi_dsi_combophy_reg.o
#endif
