# Makefile for the Linux video drivers on sunxi platform.
# 30 Sep 2016, Tyle, <mailto:tyle@allwinnertech.com>
# Rewritten to use lists instead of if-statements.
#
# Each configuration option enables a list of files.

obj-$(CONFIG_AW_DISP2) += disp2/disp/

obj-$(CONFIG_AW_HDMI_DISP2) += disp2/hdmi/

obj-$(CONFIG_AW_HDMI2_DISP2_SUNXI) += disp2/hdmi2/

obj-$(CONFIG_HDMI_EP952_AW_DISP2) += disp2/hdmi_ep952/

obj-$(CONFIG_AW_HDMI_FPGA_INNOPHY_DISP2) += disp2/hdmi_fpga_innophy/

obj-$(CONFIG_TV_AW_DISP2) += disp2/tv/

obj-$(CONFIG_DISP2_TV_AC200) += disp2/tv/

obj-$(CONFIG_VDPO_AW_DISP2) += disp2/vdpo/

obj-$(CONFIG_EDP_AW_DISP2) += disp2/edp/

obj-$(CONFIG_EDP2_AW_DISP2) += disp2/edp2/

obj-$(CONFIG_EINK200_SUNXI) += disp2/eink200/

obj-$(CONFIG_LCD_FB) += lcd_fb/

obj-$(CONFIG_TV_DECODER_DISPLAY) += dec/
