ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/common
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/common/isp_hw_if
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/sensor
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/isp
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/platform
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/platform/hdmi
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/platform/logger
ccflags-y += -I$(srctree)/drivers/misc/

obj-y += armcb_camera_io_drv.o
obj-y += armcb_v4l_sd.o
obj-y += system_dma.o
obj-y += isp_hw_if/
