NOSTDINC_FLAGS := -I$(srctree)/drivers/net/wireless/xr819/include/

obj-$(CONFIG_XR819_WLAN) += umac/
obj-$(CONFIG_XR819_WLAN) += wlan/

clean-files += Module.symvers Module.markers modules modules.order
