# SPDX-License-Identifier: GPL-2.0-or-later
#
# Allwinner audio misc driver Makefile
#
# Copyright(c) 2022-2027 Allwinnertech Co., Ltd.

# misc - test clk
snd_soc_sunxi_test_clk-objs		+= snd_sunxi_test_clk.o
obj-$(CONFIG_SND_SOC_SUNXI_TEST_CLK)		+= snd_soc_sunxi_test_clk.o

# misc - loopback
snd_soc_sunxi_loopback-objs			+= snd_sunxi_loopback.o
snd_soc_sunxi_loopback-objs			+= snd_sunxi_pcm_loopback.o
obj-$(CONFIG_SND_SOC_SUNXI_LOOPBACK)		+= snd_soc_sunxi_loopback.o
