# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I $(srctree)/drivers/bus
obj-$(CONFIG_AW_MBUS_SUN50IW9)	+= sunxi_mbus_sun50iw9.o
obj-$(CONFIG_AW_MBUS_SUN8IW11)	+= sunxi_mbus_sun8iw11.o
obj-$(CONFIG_AW_MBUS_SUN8IW18)	+= sunxi_mbus_sun8iw18.o
obj-$(CONFIG_AW_MBUS_SUN8IW20)	+= sunxi_mbus_sun8iw20.o
obj-$(CONFIG_AW_MBUS_SUN8IW21)	+= sunxi_mbus_sun8iw21.o
obj-$(CONFIG_AW_MBUS_GENERIC)	+= sunxi_mbus_generic.o
