# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_HISYSEVENT)		+= hiview_hisysevent.o
# add lightweight writing feature
obj-$(CONFIG_HISYSEVENT)		+= hisysevent_builder.o
obj-$(CONFIG_HISYSEVENT)		+= hisysevent_raw_data_encoder.o
obj-$(CONFIG_HISYSEVENT)		+= hisysevent_raw_data.o
