/* SPDX-License-Identifier: GPL-2.0 */

#ifndef NPT_REGDEFINE_H_INCLUDED
#define NPT_REGDEFINE_H_INCLUDED
//------------------------------------------------------------------------------
// REGISTER BASE
//------------------------------------------------------------------------------
#ifndef NIEUPORT_BASE
//#define NIEUPORT_BASE (0xB00)
#define NIEUPORT_BASE (0x0)

#endif

#ifndef MMU_BASE
#define MMU_BASE (0x500)
#endif

//===================================================================================
// NIEUPORT REGISTERS
//===================================================================================
#define MJPEG_PIC_START_REG         (NIEUPORT_BASE + 0x0000)
#define MJPEG_PIC_STATUS_REG        (NIEUPORT_BASE + 0x0004)
#define MJPEG_PIC_ERRMB_REG         (NIEUPORT_BASE + 0x0008)
#define MJPEG_PIC_SETMB_REG         (NIEUPORT_BASE + 0x000C)

#define MJPEG_PIC_CTRL_REG          (NIEUPORT_BASE + 0x0010)
#define MJPEG_PIC_SIZE_REG          (NIEUPORT_BASE + 0x0014)
#define MJPEG_MCU_INFO_REG          (NIEUPORT_BASE + 0x0018)
#define MJPEG_ROT_INFO_REG          (NIEUPORT_BASE + 0x001C)

#define MJPEG_SCL_INFO_REG          (NIEUPORT_BASE + 0x0020)
#define MJPEG_IF_INFO_REG           (NIEUPORT_BASE + 0x0024)
#define MJPEG_CLP_INFO_REG          (NIEUPORT_BASE + 0x0028)
#define MJPEG_OP_INFO_REG           (NIEUPORT_BASE + 0x002C)

#define MJPEG_DPB_CONFIG_REG        (NIEUPORT_BASE + 0x0030)
#define MJPEG_DPB_BASE00_REG        (NIEUPORT_BASE + 0x0034)
#define MJPEG_DPB_BASE01_REG        (NIEUPORT_BASE + 0x0038)
#define MJPEG_DPB_BASE02_REG        (NIEUPORT_BASE + 0x003C)
#define MJPEG_DPB_BASE10_REG        (NIEUPORT_BASE + 0x0040)
#define MJPEG_DPB_BASE11_REG        (NIEUPORT_BASE + 0x0044)
#define MJPEG_DPB_BASE12_REG        (NIEUPORT_BASE + 0x0048)
#define MJPEG_DPB_BASE20_REG        (NIEUPORT_BASE + 0x004C)
#define MJPEG_DPB_BASE21_REG        (NIEUPORT_BASE + 0x0050)
#define MJPEG_DPB_BASE22_REG        (NIEUPORT_BASE + 0x0054)
#define MJPEG_DPB_BASE30_REG        (NIEUPORT_BASE + 0x0058)
#define MJPEG_DPB_BASE31_REG        (NIEUPORT_BASE + 0x005C)
#define MJPEG_DPB_BASE32_REG        (NIEUPORT_BASE + 0x0060)
#define MJPEG_DPB_YSTRIDE_REG       (NIEUPORT_BASE + 0x0064)
#define MJPEG_DPB_CSTRIDE_REG       (NIEUPORT_BASE + 0x0068)
#define MJPEG_WRESP_CHECK_REG       (NIEUPORT_BASE + 0x006C)

#define MJPEG_CLP_BASE_REG          (NIEUPORT_BASE + 0x0070)
#define MJPEG_CLP_SIZE_REG          (NIEUPORT_BASE + 0x0074)
#define MJPEG_HUFF_CTRL_REG         (NIEUPORT_BASE + 0x0080)
#define MJPEG_HUFF_ADDR_REG         (NIEUPORT_BASE + 0x0084)
#define MJPEG_HUFF_DATA_REG         (NIEUPORT_BASE + 0x0088)
#define MJPEG_QMAT_CTRL_REG         (NIEUPORT_BASE + 0x0090)
#define MJPEG_QMAT_ADDR_REG         (NIEUPORT_BASE + 0x0094)
#define MJPEG_QMAT_DATA_REG         (NIEUPORT_BASE + 0x0098)
#define MJPEG_COEF_CTRL_REG         (NIEUPORT_BASE + 0x00A0)
#define MJPEG_COEF_ADDR_REG         (NIEUPORT_BASE + 0x00A4)
#define MJPEG_COEF_DATA_REG         (NIEUPORT_BASE + 0x00A8)
#define MJPEG_RST_INTVAL_REG        (NIEUPORT_BASE + 0x00B0)
#define MJPEG_RST_INDEX_REG         (NIEUPORT_BASE + 0x00B4)
#define MJPEG_RST_COUNT_REG         (NIEUPORT_BASE + 0x00B8)
#define MJPEG_INTR_MASK_REG         (NIEUPORT_BASE + 0x00C0)
#define MJPEG_CYCLE_INFO_REG        (NIEUPORT_BASE + 0x00C8)
#define MJPEG_DPCM_DIFF_Y_REG       (NIEUPORT_BASE + 0x00F0)
#define MJPEG_DPCM_DIFF_CB_REG      (NIEUPORT_BASE + 0x00F4)
#define MJPEG_DPCM_DIFF_CR_REG      (NIEUPORT_BASE + 0x00F8)

// GBU
#define MJPEG_GBU_CTRL_REG          (NIEUPORT_BASE + 0x0100)
#define MJPEG_GBU_PBIT_BUSY_REG     (NIEUPORT_BASE + 0x0104)
#define MJPEG_GBU_BT_PTR_REG        (NIEUPORT_BASE + 0x0110)
#define MJPEG_GBU_WD_PTR_REG        (NIEUPORT_BASE + 0x0114)
#define MJPEG_GBU_TT_CNT_REG        (NIEUPORT_BASE + 0x0118)
#define MJPEG_GBU_PBIT_08_REG       (NIEUPORT_BASE + 0x0120)
#define MJPEG_GBU_PBIT_16_REG       (NIEUPORT_BASE + 0x0124)
#define MJPEG_GBU_PBIT_24_REG       (NIEUPORT_BASE + 0x0128)
#define MJPEG_GBU_PBIT_32_REG       (NIEUPORT_BASE + 0x012C)
#define MJPEG_GBU_BBSR_REG          (NIEUPORT_BASE + 0x0140)
#define MJPEG_GBU_BBER_REG          (NIEUPORT_BASE + 0x0144)
#define MJPEG_GBU_BBIR_REG          (NIEUPORT_BASE + 0x0148)
#define MJPEG_GBU_BBHR_REG          (NIEUPORT_BASE + 0x014C)
#define MJPEG_GBU_BCNT_REG          (NIEUPORT_BASE + 0x0158)
#define MJPEG_GBU_FF_RPTR_REG       (NIEUPORT_BASE + 0x0160)
#define MJPEG_GBU_FF_WPTR_REG       (NIEUPORT_BASE + 0x0164)

// BBC
#define MJPEG_BBC_END_ADDR_REG      (NIEUPORT_BASE + 0x0208)
#define MJPEG_BBC_WR_PTR_REG        (NIEUPORT_BASE + 0x020C)
#define MJPEG_BBC_RD_PTR_REG        (NIEUPORT_BASE + 0x0210)
#define MJPEG_BBC_EXT_ADDR_REG      (NIEUPORT_BASE + 0x0214)
#define MJPEG_BBC_INT_ADDR_REG      (NIEUPORT_BASE + 0x0218)
#define MJPEG_BBC_DATA_CNT_REG      (NIEUPORT_BASE + 0x021C)
#define MJPEG_BBC_COMMAND_REG       (NIEUPORT_BASE + 0x0220)
#define MJPEG_BBC_BUSY_REG          (NIEUPORT_BASE + 0x0224)
#define MJPEG_BBC_CTRL_REG          (NIEUPORT_BASE + 0x0228)
#define MJPEG_BBC_CUR_POS_REG       (NIEUPORT_BASE + 0x022C)
#define MJPEG_BBC_BAS_ADDR_REG      (NIEUPORT_BASE + 0x0230)
#define MJPEG_BBC_STRM_CTRL_REG     (NIEUPORT_BASE + 0x0234)
#define MJPEG_BBC_FLUSH_CMD_REG     (NIEUPORT_BASE + 0x0238)

#define JPU_MMU_TRI (NIEUPORT_BASE +0x400)

#define TBU_NUM 32
#define MJPEG_MMU_TTBLR_BASE         (MMU_BASE + 0x40)
#define MJPEG_MMU_TTBHR_BASE         (MMU_BASE + 0x44)
#define MJPEG_MMU_TCR0_BASE          (MMU_BASE + 0x48)
#define MJPEG_MMU_TCR1_BASE          (MMU_BASE + 0x4c)
#define MJPEG_MMU_TBU_STATUS_BASE    (MMU_BASE + 0x50)
#define MJPEG_MMU_TBUx_STEP          0x20
#define MJPEG_MMU_BVA_LO             (MMU_BASE + 0x00)
#define MJPEG_MMU_BVA_HI             (MMU_BASE + 0x04)
#define MJPEG_MMU_TIMEOUT_VA_ADDR_LO (MMU_BASE + 0x08)
#define MJPEG_MMU_TIMEOUT_VA_ADDR_HI (MMU_BASE + 0x0C)
#define MJPEG_MMU_IRQ_STATUS         (MMU_BASE + 0x10)
#define MJPEG_MMU_IRQ_ENABLE         (MMU_BASE + 0x14)
#define MJPEG_MMU_TIMEOUT_VALUE      (MMU_BASE + 0x18)
#define MJPEG_MMU_ERROR_CLEAR        (MMU_BASE + 0x1C)
#define MJPEG_MMU_LAST_VA_ADDR_LO    (MMU_BASE + 0x20)
#define MJPEG_MMU_LAST_VA_ADDR_HI    (MMU_BASE + 0x24)
#define MJPEG_MMU_LAST_PA_ADDR_LO    (MMU_BASE + 0x28)
#define MJPEG_MMU_LAST_PA_ADDR_HI    (MMU_BASE + 0x2C)
#define MJPEG_MMU_VERSION            (MMU_BASE + 0x3C)

#define BASE_VIRTUAL_ADDRESS	0x80000000
#define VA_STEP_PER_TBU		0x2000000
#define MAX_ENTRIES_PER_TTB	8096
#define ENTRY_SIZE		4
#define MAX_SIZE_PER_TTB	(MAX_ENTRIES_PER_TTB*ENTRY_SIZE)
#define DEFAULT_TIMEOUT_CYCS	0x80000
#define KY_MJPEG_MMU_PGSIZE_BITMAP 0x02FFF000	/* 4K~32M */

#define TBU_INSTANCES_NUM	2

#define TTB_ENTRY_SHIFT		12
#define AQUIRE_TIMEOUT_MS	100
#endif
