ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/platform
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/common
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/common/isp_hw_if
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/platform/logger

obj-y += armcb_v4l2_config.o
obj-y += armcb_v4l2_core.o
obj-y += armcb_v4l2_stream.o
obj-y += armcb_vb2.o
obj-y += armcb_isp_driver.o
