# SPDX-License-Identifier: GPL-2.0-only

ccflags-y += -I $(srctree)/bsp/drivers/gmac
obj-$(CONFIG_AW_GMAC) += sunxi-gmac.o
obj-$(CONFIG_AW_GMAC_MDIO) += sunxi-mdio.o
obj-$(CONFIG_AW_EPHY) += sunxi-ephy.o
