# SPDX-License-Identifier: GPL-2.0
#
# Makefile for wifi bluetooth power controller drivers
#

sunxi_rfkill-objs := sunxi-gnss.o sunxi-modem.o sunxi-bluetooth.o sunxi-wlan.o sunxi-rfkill.o

obj-$(CONFIG_AW_RFKILL)   += sunxi_rfkill.o
