# SPDX-License-Identifier: GPL-2.0

# Makefile for the cache exception drivers.
#
# Each configuration option enables a list of files.

obj-$(CONFIG_PLAT_CACHE_EXCEPTION_MONITOR)		+= cache_exception_interface.o cache_core_exception_drv.o cache_dsu_exception_drv.o
