obj-$(CONFIG_AW_AXP) += axp-mfd.o
obj-$(CONFIG_AW_AXP) += axp-rw.o
obj-$(CONFIG_AW_AXP) += axp-script.o
obj-$(CONFIG_AW_AXP) += axp-depend-init.o
obj-$(CONFIG_AW_AXP) += axp-depend-set.o
obj-$(CONFIG_AW_AXP) += axp-regu-script.o
obj-$(CONFIG_AW_AXP) += axp-interface.o

#Make this built-in, so that it will be loaded before I2C driver
#AXP22x
obj-$(CONFIG_AW_AXP22) += axp22-board.o
obj-$(CONFIG_AW_AXP22) += axp22-regu.o
obj-$(CONFIG_AW_AXP22) += axp22-sply.o
obj-$(CONFIG_AW_AXP22) += virtual22.o
obj-$(CONFIG_AW_AXP22) += virtual22_dev.o
obj-$(CONFIG_AW_AXP22) += axp-debugfs.o
#AXP15x
obj-$(CONFIG_AW_AXP15) += axp15-board.o
obj-$(CONFIG_AW_AXP15) += axp15-regu.o
obj-$(CONFIG_AW_AXP15) += virtual15.o
obj-$(CONFIG_AW_AXP15) += virtual15_dev.o
obj-$(CONFIG_AXP15_IRQ)+= axp15-irq.o
#AXP81x
obj-$(CONFIG_AW_AXP81X) += axp81x/axp81x-board.o
obj-$(CONFIG_AW_AXP81X) += axp81x/axp81x-board-device.o
obj-$(CONFIG_AW_AXP81X) += axp81x/axp81x-regu.o
obj-$(CONFIG_AW_AXP81X) += axp81x/axp81x-sply.o
obj-$(CONFIG_AW_AXP81X) += axp81x/virtual81x.o
obj-$(CONFIG_AW_AXP81X) += axp81x/virtual81x_dev.o
obj-$(CONFIG_AW_AXP81X) += axp81x/axp81x-init.o
obj-$(CONFIG_AW_AXP81X) += axp-regu.o
obj-$(CONFIG_AW_AXP81X) += axp-irq.o
obj-$(CONFIG_AW_AXP81X) += axp-state.o
obj-$(CONFIG_AW_AXP81X) += axp-chg.o
obj-$(CONFIG_AW_AXP81X) += axp-filenode.o
obj-$(CONFIG_AW_AXP81X) += axp-chipid.o
#AXP19x
obj-$(CONFIG_AW_AXP19) += axp19/axp19-board.o
obj-$(CONFIG_AW_AXP19) += axp19/axp19-regu.o
obj-$(CONFIG_AW_AXP19) += axp19/axp19-sply.o
obj-$(CONFIG_AW_AXP19) += axp19/axp19-init.o
obj-$(CONFIG_AW_AXP19) += axp19/virtual19.o
obj-$(CONFIG_AW_AXP19) += axp19/virtual19_dev.o
obj-$(CONFIG_AW_AXP19) += axp-regu.o
obj-$(CONFIG_AW_AXP19) += axp-irq.o
obj-$(CONFIG_AW_AXP19) += axp-state.o
obj-$(CONFIG_AW_AXP19) += axp-filenode.o
#AXP20
obj-$(CONFIG_AW_AXP20) += axp20/axp20-board.o
obj-$(CONFIG_AW_AXP20) += axp20/axp20-init.o
obj-$(CONFIG_AW_AXP20) += axp20/axp20-regu.o
obj-$(CONFIG_AW_AXP20_OCV) += axp20/axp20-sply.o
obj-$(CONFIG_AW_AXP20_COU) += axp20/axp20-sply-cou.o
obj-$(CONFIG_AW_AXP20) += axp20/virtual20.o
obj-$(CONFIG_AW_AXP20) += axp20/virtual20_dev.o

