obj-$(CONFIG_AW_AXP) += axp-core.o
obj-$(CONFIG_AW_AXP) += axp-powerkey.o
obj-$(CONFIG_AW_AXP) += axp-depend-init.o
obj-$(CONFIG_AW_AXP) += axp-depend-set.o
obj-$(CONFIG_AW_AXP) += axp-charger.o
obj-$(CONFIG_AW_AXP) += axp-gpio.o
obj-$(CONFIG_AW_AXP) += axp-regulator.o
obj-$(CONFIG_AXP_NMI_USED) += nmi/sunxi-nmi.o

#AXP15X
obj-$(CONFIG_AW_AXP15) += axp15/axp15.o
obj-$(CONFIG_AW_AXP15) += axp15/axp15-regu.o
obj-$(CONFIG_AW_AXP15) += axp15/axp15-gpio.o
obj-$(CONFIG_AW_AXP15) += axp15/axp15-powerkey.o
obj-$(CONFIG_AW_AXP15) += axp15/virtual15.o
obj-$(CONFIG_AW_AXP15) += axp15/virtual15_dev.o

#AXP22X
obj-$(CONFIG_AW_AXP22) += axp22/axp22.o
obj-$(CONFIG_AW_AXP22) += axp22/axp22-regu.o
obj-$(CONFIG_AW_AXP22) += axp22/axp22-charger.o
obj-$(CONFIG_AW_AXP22) += axp22/axp22-gpio.o
obj-$(CONFIG_AW_AXP22) += axp22/axp22-powerkey.o
obj-$(CONFIG_AW_AXP22) += axp22/virtual22.o
obj-$(CONFIG_AW_AXP22) += axp22/virtual22_dev.o

#AXP259
obj-$(CONFIG_AW_AXP259) += axp259/axp259.o
obj-$(CONFIG_AW_AXP259) += axp259/axp259-charger.o
obj-$(CONFIG_AW_AXP259) += axp259/axp259-powerkey.o

#AXP22X
obj-$(CONFIG_AW_AXP20) += axp20/axp20.o
obj-$(CONFIG_AW_AXP20) += axp20/axp20-regu.o
obj-$(CONFIG_AW_AXP20) += axp20/axp20-charger.o
obj-$(CONFIG_AW_AXP20) += axp20/axp20-gpio.o
obj-$(CONFIG_AW_AXP20) += axp20/axp20-powerkey.o
obj-$(CONFIG_AW_AXP20) += axp20/virtual20.o
obj-$(CONFIG_AW_AXP20) += axp20/virtual20_dev.o

#AXP80X
obj-$(CONFIG_AW_AXP80) += axp80/axp80.o
obj-$(CONFIG_AW_AXP80) += axp80/axp80-regu.o
obj-$(CONFIG_AW_AXP80) += axp80/axp80-gpio.o
obj-$(CONFIG_AW_AXP80) += axp80/axp80-powerkey.o
obj-$(CONFIG_AW_AXP80) += axp80/virtual80.o
obj-$(CONFIG_AW_AXP80) += axp80/virtual80_dev.o

#AXPDUMMY
obj-$(CONFIG_AW_AXPDUMMY) += axpdummy/axpdummy.o
obj-$(CONFIG_AW_AXPDUMMY) += axpdummy/axpdummy-regu.o
obj-$(CONFIG_AW_AXPDUMMY) += axpdummy/virtualdummy.o
obj-$(CONFIG_AW_AXPDUMMY) += axpdummy/virtualdummy_dev.o
