# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_AW_INNO_COMBOPHY)	+= sunxi-inno-combophy.o
obj-$(CONFIG_AW_CADENCE_COMBOPHY) += sunxi-cadence-combophy.o
obj-$(CONFIG_AW_SYNOPSYS_COMBOPHY) += sunxi-synopsys-combophy.o
