/* SPDX-License-Identifier: GPL-2.0 */
/*
 * regs-cpp-v2p0.h
 *
 * register settings for KY X1 Camera Post Process
 *
 * Copyright (C) 2023 KY Micro Limited
 */

#ifndef __REGS_CPP_V2P0_H__
#define __REGS_CPP_V2P0_H__

#define REG_CPP_3DNR_BST_LEN	(0x018C)
#define REG_CPP_3DNR_CG_CTRL	(0x0194)
#define REG_CPP_3DNR_TOP_CTRL	(0x01bc)
#define REG_CPP_QUEUE_CTRL	(0x7000)
#define REG_CPP_IRQ_STATUS	(0x7004)
#define REG_CPP_IRQ_MASK	(0x7008)
#define REG_CPP_IRQ_RAW		(0x700C)
#define REG_CPP_CHIP_ID		(0x7020)

/* REG_CPP_QUEUE_CTRL */
#define QCTRL_GLB_RST_CYC_MASK	(0xff << 24)
#define QCTRL_AXI_FAB_CG	(0x1 << 18)
#define QCTRL_FBC_ENC_CG	(0x1 << 17)
#define QCTRL_QUEUE_CG		(0x1 << 16)
#define QCTRL_QUEUE_FBC		(0x1 << 12)
#define QCTRL_GLB_RST		(0x1 << 1)

/* REG_CPP_IRQ_STATUS */
#define QIRQ_STAT_3DNR_EOF	(0x1 << 14)
#define QIRQ_STAT_IOMMU		(0x1 << 13)
#define QIRQ_STAT_FBC_ENC	(0x1 << 12)
#define QIRQ_STAT_FBC_DEC1	(0x1 << 11)
#define QIRQ_STAT_FBC_DEC0	(0x1 << 10)
#define QIRQ_STAT_GLB_RST_DONE	(0x1 << 9)
#define QIRQ_STAT_RDMA_TIMEOUT	(0x1 << 8)
#define QIRQ_STAT_WDMA_TIMEOUT	(0x1 << 7)
#define QIRQ_STAT_DMAC_RD_ERR	(0x1 << 6)
#define QIRQ_STAT_DMAC_WR_ERR	(0x1 << 5)
#define QIRQ_STAT_RDMA_DONE	(0x1 << 4)
#define QIRQ_STAT_TOP_CTRL_DONE	(0x1 << 3)
#define QIRQ_STAT_SLC_START	(0x1 << 2)
#define QIRQ_STAT_SLC_DONE	(0x1 << 1)
#define QIRQ_STAT_FRM_DONE	(0x1 << 0)

/* REG_CPP_IRQ_MASK */
#define QIRQ_MASK_ERR						\
	(QIRQ_STAT_RDMA_TIMEOUT | QIRQ_STAT_WDMA_TIMEOUT |	\
	 QIRQ_STAT_DMAC_RD_ERR | QIRQ_STAT_DMAC_WR_ERR)

#define QIRQ_MASK_FBC						\
	(QIRQ_STAT_FBC_ENC | QIRQ_STAT_FBC_DEC0)

#define QIRQ_MASK_IOMMU (QIRQ_STAT_IOMMU)

#define QIRQ_MASK_GEN						\
	(QIRQ_MASK_ERR | QIRQ_STAT_GLB_RST_DONE | QIRQ_STAT_FRM_DONE |		\
	 QIRQ_MASK_FBC | QIRQ_MASK_IOMMU)

#define REG_CPP_YINPUTBASEADDR_L4  (0x144)
#define REG_CPP_YINPUTBASEADDR_L3  (0x148)
#define REG_CPP_YINPUTBASEADDR_L2  (0x14c)
#define REG_CPP_YINPUTBASEADDR_L1  (0x150)
#define REG_CPP_YINPUTBASEADDR_L0  (0x154)
#define REG_CPP_UVINPUTBASEADDR_L4 (0x158)
#define REG_CPP_UVINPUTBASEADDR_L3 (0x15c)
#define REG_CPP_UVINPUTBASEADDR_L2 (0x160)
#define REG_CPP_UVINPUTBASEADDR_L1 (0x164)
#define REG_CPP_UVINPUTBASEADDR_L0 (0x168)

#define REG_CPP_PRE_YINPUTBASEADDR_L4  (0x2a0)
#define REG_CPP_PRE_YINPUTBASEADDR_L3  (0x2a4)
#define REG_CPP_PRE_YINPUTBASEADDR_L2  (0x2a8)
#define REG_CPP_PRE_YINPUTBASEADDR_L1  (0x2ac)
#define REG_CPP_PRE_YINPUTBASEADDR_L0  (0x2b0)
#define REG_CPP_PRE_UVINPUTBASEADDR_L4 (0x2b4)
#define REG_CPP_PRE_UVINPUTBASEADDR_L3 (0x2b8)
#define REG_CPP_PRE_UVINPUTBASEADDR_L2 (0x2bc)
#define REG_CPP_PRE_UVINPUTBASEADDR_L1 (0x2c0)
#define REG_CPP_PRE_UVINPUTBASEADDR_L0 (0x2c4)
#define REG_CPP_PRE_KINPUTBASEADDR_L4  (0x2c8)
#define REG_CPP_PRE_KINPUTBASEADDR_L3  (0x2cc)
#define REG_CPP_PRE_KINPUTBASEADDR_L2  (0x2d0)
#define REG_CPP_PRE_KINPUTBASEADDR_L1  (0x2d4)
#define REG_CPP_PRE_KINPUTBASEADDR_L0  (0x2d8)

#define REG_CPP_YWBASEADDR_L4  (0x2f0)
#define REG_CPP_YWBASEADDR_L3  (0x2f4)
#define REG_CPP_YWBASEADDR_L2  (0x2f8)
#define REG_CPP_YWBASEADDR_L1  (0x2fc)
#define REG_CPP_YWBASEADDR_L0  (0x300)
#define REG_CPP_UVWBASEADDR_L4 (0x304)
#define REG_CPP_UVWBASEADDR_L3 (0x308)
#define REG_CPP_UVWBASEADDR_L2 (0x30c)
#define REG_CPP_UVWBASEADDR_L1 (0x310)
#define REG_CPP_UVWBASEADDR_L0 (0x314)
#define REG_CPP_KWBASEADDR_L4  (0x318)
#define REG_CPP_KWBASEADDR_L3  (0x31c)
#define REG_CPP_KWBASEADDR_L2  (0x320)
#define REG_CPP_KWBASEADDR_L1  (0x324)
#define REG_CPP_KWBASEADDR_L0  (0x328)

/* DMA address high extension */
#define REG_CPP_YINPUTBASEADDR_L4_H  (0x354)
#define REG_CPP_YINPUTBASEADDR_L3_H  (0x358)
#define REG_CPP_YINPUTBASEADDR_L2_H  (0x35c)
#define REG_CPP_YINPUTBASEADDR_L1_H  (0x360)
#define REG_CPP_YINPUTBASEADDR_L0_H  (0x364)
#define REG_CPP_UVINPUTBASEADDR_L4_H (0x368)
#define REG_CPP_UVINPUTBASEADDR_L3_H (0x36c)
#define REG_CPP_UVINPUTBASEADDR_L2_H (0x370)
#define REG_CPP_UVINPUTBASEADDR_L1_H (0x374)
#define REG_CPP_UVINPUTBASEADDR_L0_H (0x378)

#define REG_CPP_PRE_YINPUTBASEADDR_L4_H  (0x37c)
#define REG_CPP_PRE_YINPUTBASEADDR_L3_H  (0x380)
#define REG_CPP_PRE_YINPUTBASEADDR_L2_H  (0x384)
#define REG_CPP_PRE_YINPUTBASEADDR_L1_H  (0x388)
#define REG_CPP_PRE_YINPUTBASEADDR_L0_H  (0x38c)
#define REG_CPP_PRE_UVINPUTBASEADDR_L4_H (0x390)
#define REG_CPP_PRE_UVINPUTBASEADDR_L3_H (0x394)
#define REG_CPP_PRE_UVINPUTBASEADDR_L2_H (0x398)
#define REG_CPP_PRE_UVINPUTBASEADDR_L1_H (0x39c)
#define REG_CPP_PRE_UVINPUTBASEADDR_L0_H (0x3a0)
#define REG_CPP_PRE_KINPUTBASEADDR_L4_H  (0x3a4)
#define REG_CPP_PRE_KINPUTBASEADDR_L3_H  (0x3a8)
#define REG_CPP_PRE_KINPUTBASEADDR_L2_H  (0x3ac)
#define REG_CPP_PRE_KINPUTBASEADDR_L1_H  (0x3b0)
#define REG_CPP_PRE_KINPUTBASEADDR_L0_H  (0x3b4)

#define REG_CPP_YWBASEADDR_L4_H  (0x3b8)
#define REG_CPP_YWBASEADDR_L3_H  (0x3bc)
#define REG_CPP_YWBASEADDR_L2_H  (0x3c0)
#define REG_CPP_YWBASEADDR_L1_H  (0x3c4)
#define REG_CPP_YWBASEADDR_L0_H  (0x3c8)
#define REG_CPP_UVWBASEADDR_L4_H (0x3cc)
#define REG_CPP_UVWBASEADDR_L3_H (0x3d0)
#define REG_CPP_UVWBASEADDR_L2_H (0x3d4)
#define REG_CPP_UVWBASEADDR_L1_H (0x3d8)
#define REG_CPP_UVWBASEADDR_L0_H (0x3dc)
#define REG_CPP_KWBASEADDR_L4_H  (0x3e0)
#define REG_CPP_KWBASEADDR_L3_H  (0x3e4)
#define REG_CPP_KWBASEADDR_L2_H  (0x3e8)
#define REG_CPP_KWBASEADDR_L1_H  (0x3ec)
#define REG_CPP_KWBASEADDR_L0_H  (0x3f0)
#endif
