obj-$(CONFIG_SND_SUN8IW6_AUDIOHUB) += sunxi-audiohub.o
obj-$(CONFIG_SND_SUN8IW7_AUDIOHUB) += sun8iw7-hubaudio.o
obj-$(CONFIG_SND_SUNXI_SOC_AUDIOHUB_INTERFACE) += sunxi-audiohubdma.o
obj-$(CONFIG_SND_SUNXI_SOC_AUDIOHUB_INTERFACE) += hubcodec.o
obj-$(CONFIG_SND_SUNXI_SOC_AUDIOHUB_INTERFACE) += sunxi-sndaudiohub.o
