# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_BCMDHD)	+= rkwifi/
obj-$(CONFIG_CYW_BCMDHD)	+= cywdhd/
obj-$(CONFIG_INFINEON_DHD)	+= infineon/

obj-$(CONFIG_RTL8852BE)		+= rtl8852be/
obj-$(CONFIG_RTL8852BU)		+= rtl8852bu/