obj-$(CONFIG_SND_SUNXI_SOC_AUDIOCODEC) += sunxi_codec.o
obj-$(CONFIG_SND_SUNXI_SOC_AUDIOCODEC) += sunxi_codecdma.o
obj-$(CONFIG_SND_SUN8IW1_SNDCODEC) += sun8iw1_sndcodec.o
obj-$(CONFIG_SND_SUN8IW3_SNDCODEC) += sun8iw3_sndcodec.o
obj-$(CONFIG_SND_SUN8IW5_SNDCODEC) += sun8iw5_sndcodec.o
obj-$(CONFIG_SND_SUN8IW7_SNDCODEC) += sun8iw7_sndcodec.o
obj-$(CONFIG_SND_SUN8IW8_SNDCODEC) += sun8iw8_sndcodec.o
obj-$(CONFIG_SND_SUN8IW9_SNDCODEC) += sun8iw9_sndcodec.o
obj-$(CONFIG_SND_SUN8IW9_SNDCODEC) += sunxi_bbcodec.o
obj-$(CONFIG_SND_SUNXI_SOC_PUBLUC_MACHINE) += sunxi_sndcodec.o
obj-$(CONFIG_SND_SUNXI_SOC_SUN8IW9_MACHINE) += sun8iw9_machine.o
obj-$(CONFIG_SND_SUNXI_SWITCH) += switch_hdset.o


