# SPDX-License-Identifier: GPL-2.0

# Minimal System
obj-y += clk/
obj-y += pinctrl/
obj-y += uart/
obj-y += timer/

# Basic System
obj-y += dma/
obj-y += rtc/
obj-y += bus/
obj-y += dumpreg/
obj-y += watchdog/
obj-y += iommu/
obj-y += mbus/
obj-y += aw_trace/

# Storage
obj-y += mmc/
obj-y += ufs/
obj-y += mtd/
obj-y += redeposit/

# Graphics
obj-y += video/
obj-y += g2d/
obj-y += di/
obj-y += vin/
obj-y += vfe/
obj-y += tvd/
obj-y += drm/
obj-y += gpu/
obj-y += car_reverse/

# Multi-Media
obj-y += ve/
obj-$(CONFIG_VIDEO_RT_MEDIA) += rt-media/

# Audio
obj-y += sound/

# Security
obj-y += ce/
obj-y += smc/
obj-y += sid/
obj-y += secure_storage/
obj-y += drm_heap/

# I/O Connectivity
obj-y += pcie/
obj-y += phy/
obj-y += emac/
obj-y += gmac/
obj-y += stmmac/
obj-y += usb/
obj-y += twi/
obj-y += spi/
obj-y += spi-ng/
obj-y += ledc/
obj-y += pwm/
obj-y += ir-tx/
obj-y += ir-rx/
obj-y += gpadc/
obj-y += lradc/
obj-y += rtp/
obj-y += input/
obj-y += ata/
obj-y += smartcard/
obj-y += wiegand/

# Wireless
obj-y += net/
obj-y += bluetooth/

# Power Management
obj-y += irqchip/
obj-y += standby/
obj-y += thermal/
obj-y += nvmem/
obj-y += pm_domain/
obj-y += power/
obj-y += cpufreq/
obj-y += devfreq/
obj-y += dsufreq/

# AMP/XPU
obj-y += msgbox/
obj-y += hwspinlock/
obj-y += remoteproc/
obj-y += rpmsg/
obj-y += rpbuf/
obj-y += npu/

# Misc
obj-y += misc/
obj-y += vendor_hooks/

# Debugging
obj-y += crashdump/
obj-y += jtag/
obj-y += debug/

# pstore
obj-y += pstore/

# FS
obj-y += fs/

obj-y += andes_adaptor/

#awlink
obj-y += awlink/

