obj-$(CONFIG_DISP2_TV_GM7121) += gm7121.o

obj-$(CONFIG_DISP2_TV_AC200) += tv_acxx.o
tv_acxx-y := tv_ac200.o tv_ac200_lowlevel.o

obj-$(CONFIG_TV_DISP2_SUNXI) += tv.o
tv-y := drv_tv.o
tv-$(CONFIG_ARCH_SUN8IW11) += de_tve_sun8iw11.o
tv-$(CONFIG_ARCH_SUN50IW2) += de_tve_v1.o
tv-$(CONFIG_ARCH_SUN8IW12) += de_tve_sun8iw11.o
tv-$(CONFIG_ARCH_SUN8IW7) += de_tve_sun8iw7.o
tv-$(CONFIG_ARCH_SUN8IW17) += de_tve_sun8iw11.o
tv-$(CONFIG_ARCH_SUN8IW16) += de_tve_sun8iw11.o
tv-$(CONFIG_ARCH_SUN50IW9) += de_tve_sun8iw11.o
tv-$(CONFIG_ARCH_SUN8IW20) += de_tve_sun8iw11.o
