obj-$(CONFIG_HDMI2_DISP2_SUNXI) += hdmi20.o

hdmi20-y := hdmi_tx.o
#hdmi20-y += hdmi_test.o

hdmi20-y += hdmi_core/core_cec.o
hdmi20-y += hdmi_core/core_edid.o
hdmi20-y += hdmi_core/hdmi_core.o


hdmi20-y += hdmi_core/api/api.o
hdmi20-y += hdmi_core/api/access.o
hdmi20-y += hdmi_core/api/cec.o

hdmi20-y += hdmi_core/api/core/audio.o
hdmi20-y += hdmi_core/api/core/fc_audio.o
hdmi20-y += hdmi_core/api/core/fc_video.o
hdmi20-y += hdmi_core/api/core/irq.o
hdmi20-y += hdmi_core/api/core/main_controller.o
hdmi20-y += hdmi_core/api/core/packets.o
hdmi20-y += hdmi_core/api/core/video.o

hdmi20-y += hdmi_core/api/edid.o
hdmi20-y += hdmi_core/api/hdcp.o
hdmi20-y += hdmi_core/api/identification.o
hdmi20-y += hdmi_core/api/phy.o
hdmi20-y += hdmi_core/api/scdc.o
hdmi20-y += hdmi_core/api/general_ops.o

hdmi20-y += hdmi_core/api/hdcp22_tx.o
hdmi20-y += hdmi_core/api/hdcp22/esm_host_lib_init.o
hdmi20-y += hdmi_core/api/hdcp22/esm_host_lib_log.o
hdmi20-y += hdmi_core/api/hdcp22/esm_host_lib_auth.o
hdmi20-y += hdmi_core/api/hdcp22/esm_host_lib_code.o
hdmi20-y += hdmi_core/api/hdcp22/esm_host_lib_exceptions.o
hdmi20-y += hdmi_core/api/hdcp22/esm_host_lib_mailbox.o
hdmi20-y += hdmi_core/api/hdcp22/esm_host_lib_status.o
