ccflags-y += -I$(srctree)/drivers/misc/cix/sensor/core
ccflags-y += -I$(srctree)/drivers/misc/cix/sensor/scp/include

obj-$(CONFIG_CIX_KERNEL_SENSORHUB) += sensorhub.o
sensorhub-objs += sensor_list.o sensorhub_ipi.o cix_sensorhub.o