# SPDX-License-Identifier: GPL-2.0

ky-drm-y := 	ky_drm.o \
				ky_cmdlist.o \
				ky_dpu.o \
				ky_planes.o \
				ky_dsi.o \
				ky_wb.o \
				ky_dphy.o \
				ky_lib.o \
				ky_gem.o \
				ky_dmmu.o \
				ky_bootloader.o \
				sysfs/sysfs_class.o \
				sysfs/sysfs_dpu.o \
				sysfs/sysfs_dsi.o \
				sysfs/sysfs_dphy.o \
				sysfs/sysfs_mipi_panel.o \
				dpu/dpu_debug.o \
				dpu/dpu_saturn.o \
				dpu/saturn_fbcmem.o \
				dsi/ky_dsi_drv.o \
				dsi/ky_dptc_drv.o \
				dphy/ky_dphy_drv.o


obj-$(CONFIG_DRM_KY) += ky-drm.o

obj-$(CONFIG_KY_MIPI_PANEL) += ky_mipi_panel.o
obj-$(CONFIG_KY_HDMI) += ky_hdmi.o
obj-$(CONFIG_DRM_LT8911EXB) += lt8911exb.o
obj-$(CONFIG_DRM_LT9711) += lt9711.o
