ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/platform
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/platform/logger
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/isp
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/common/isp_hw_if
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/common

obj-y += armcb_actuator.o
