# SPDX-License-Identifier: GPL-2.0

# Keep the list ordered.
obj-$(CONFIG_AW_RTC)		+= rtc-sunxi.o
obj-$(CONFIG_AW_TIMER_ALARM)	+= sunxi_timer_alarm.o
obj-$(CONFIG_RTC_DRV_SD2059)	+= rtc-sd2059.o
obj-$(CONFIG_RTC_DRV_JXR160)	+= rtc-jxr160.o
