# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_CIX_SKY1_SOCINFO) += cix-sky1-socinfo.o
obj-$(CONFIG_CIX_SKY1_E_SHUTTER) += cloudbook-e-shutter.o
obj-$(CONFIG_CIX_DST) += cix_dst/
obj-$(CONFIG_CIX_SOC_ACPI) += acpi/
obj-$(CONFIG_ARCH_CIX) += cix-plat.o
obj-y += cix-hibernate.o
