# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the sensor drivers.
#
# Each configuration option enables a list of files.


obj-$(CONFIG_AW_INPUT_SENSOR)    += sc7a20/
obj-$(CONFIG_AW_INPUT_SENSOR)    += stk3x1x/
obj-$(CONFIG_AW_INPUT_SENSOR)    += mir3da/
obj-$(CONFIG_AW_INPUT_SENSOR)    += msa/
obj-$(CONFIG_AW_INPUT_SENSOR)    += mmc5603/
obj-$(CONFIG_AW_INPUT_SENSOR)    += bmi323/
obj-$(CONFIG_AW_INPUT_SENSOR)    += qmi8658/

