#
# Makefile for the sunxi cpu budget cooling drivers.
#
#obj-$(CONFIG_SUNXI_BUDGET_COOLING) += sunxi-budget.o
obj-$(CONFIG_SUNXI_BUDGET_COOLING) += sunxi-budget-cooling.o
#sunxi-budget-y += sunxi-budget-cooling.o
obj-$(CONFIG_SUNXI_BUDGET_COOLING_CPU_DVFS) += sunxi-budget-cooling-dvfs.o
obj-$(CONFIG_SUNXI_BUDGET_COOLING_HOTPLUG) += sunxi-budget-cooling-hotplug.o
obj-$(CONFIG_SUNXI_GPU_COOLING) += sunxi_gpu_cooling.o
