# SPDX-License-Identifier: (GPL-2.0-only OR BSD-3-Clause)
snd-sof-cix-common-objs := cix-common.o
snd-sof-cix-sky1-objs := cix-sky1.o

obj-$(CONFIG_SND_SOC_SOF_CIX_COMMON) += snd-sof-cix-common.o
obj-$(CONFIG_SND_SOC_SOF_CIX_SKY1) += snd-sof-cix-sky1.o
