# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the sensor drivers.
#
# Each configuration option enables a list of files.


obj-$(CONFIG_AW_INPUT_MISC)    += hall_sensor/
obj-$(CONFIG_AW_INPUT_MISC)    += vibrator/
