#ifndef __CLK_SUN8IW3_H
#define __CLK_SUN8IW3_H
 
 
#define LOSC_CLK "losc"
#define HOSC_CLK "hosc"
#define PLL2X8_CLK "pll2x8"
#define PLL2X4_CLK "pll2x4"
#define PLL2X2_CLK "pll2x2"
#define PLL3X2_CLK "pll3x2"
#define PLL6X2_CLK "pll6x2"
#define HOSCD2_CLK "hoscd2"
#define PLL1_CLK "pll1"
#define PLL2_CLK "pll2"
#define PLL3_CLK "pll3"
#define PLL4_CLK "pll4"
#define PLL5_CLK "pll5"
#define PLL6_CLK "pll6"
#define PLL8_CLK "pll8"
#define PLL9_CLK "pll9"
#define PLL10_CLK "pll10"
#define PLL_MIPI_CLK "pll_mipi"
#define CPU_CLK "cpu"
#define AXI_CLK "axi"
#define PLL6AHB1_CLK "pll6ahb1"
#define AHB1_CLK "ahb1"
#define APB1_CLK "apb1"
#define APB2_CLK "apb2"
#define NAND_CLK "nand"
#define SDMMC0_CLK "sdmmc0"
#define SDMMC1_CLK "sdmmc1"
#define SDMMC2_CLK "sdmmc2"
#define SPI0_CLK "spi0"
#define SPI1_CLK "spi1"
#define I2S0_CLK "i2s0"
#define I2S1_CLK "i2s1"
#define USBOHCI_CLK "usbohci"
#define USBHSIC_CLK "usbhsic"
#define USBEHCI_CLK "usbehci"
#define USBOTG_CLK "usbotg"
#define USBPHY0_CLK "usbphy0"
#define USBPHY1_CLK "usbphy1"
#define DEBE0_CLK "debe0"
#define DEFE0_CLK "defe0"
#define LCD0CH0_CLK "lcd0ch0"
#define CSI_S_CLK "csi_s"
#define CSI_M_CLK "csi_m"
#define VE_CLK "ve"
#define LVDS_CLK "lvds"
#define ADDA_CLK "adda"
#define AVS_CLK "avs"
#define MBUS_CLK "mbus"
#define MIPIDSI_CLK "mipidsi"
#define MIPIDPHY_CLK "mipidphy"
#define DRC0_CLK "drc0"
#define GPU_CLK "gpu"
#define ATS_CLK "ats"
#define SPINLOCK_CLK "spinlock"
#define MSGBOX_CLK "msgbox"
#define DMA_CLK "dma"
#define PIO_CLK "pio"
#define TWI0_CLK "twi0"
#define TWI1_CLK "twi1"
#define TWI2_CLK "twi2"
#define UART0_CLK "uart0"
#define UART1_CLK "uart1"
#define UART2_CLK "uart2"
#define UART3_CLK "uart3"
#define UART4_CLK "uart4"
#define LOSC_OUT_CLK "losc_out"
 
 
#endif
