dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-orangepi-4.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-orangepi-4-lcd1.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-orangepi-800.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
