obj-$(CONFIG_SND_SUN9I_8IW6_HDMIPCM) += sunxi-hdmiaudio.o
obj-$(CONFIG_SND_SUN8IW7_HDMIPCM) += sunxi-hdmitdm.o
obj-$(CONFIG_SND_SUNXI_SOC_HDMIAUDIO) += sunxi-hdmipcm.o
obj-$(CONFIG_SND_SUNXI_SOC_HDMIAUDIO) += sndhdmi.o
obj-$(CONFIG_SND_SUNXI_SOC_HDMIAUDIO) += sunxi-sndhdmi.o
