# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core drivers.
#
# Each configuration option enables a list of files.

obj-$(CONFIG_AW_INPUT_SENSORINIT)   += init-input.o

obj-$(CONFIG_AW_INPUT_CTP)    += ctp/
obj-$(CONFIG_AW_INPUT_SENSOR)    += sensor/
obj-$(CONFIG_AW_INPUT_MISC)    += misc/
