obj-$(CONFIG_FB_SUNXI_LEGACY) += disp.o

disp-objs :=  dev_disp.o dev_fb.o dev_capture.o dev_disp_attrnode.o\
							OSAL/OSAL_Cache.o OSAL/OSAL_Clock.o OSAL/OSAL_Dma.o OSAL/OSAL_Int.o OSAL/OSAL_IrqLock.o  OSAL/OSAL_Pwm.o\
							OSAL/OSAL_Lib_C.o OSAL/OSAL_Pin.o OSAL/OSAL_Semi.o OSAL/OSAL_Thread.o OSAL/OSAL_Time.o OSAL/OSAL_Parser.o\
							de_bsp/de/ebios/de_be.o de_bsp/de/ebios/de_fe.o de_bsp/de/ebios/de_hwc.o\
							de_bsp/de/ebios/de_layer.o de_bsp/de/ebios/de_lcd.o de_bsp/de/ebios/de_tve.o de_bsp/de/ebios/de_dsi.o\
							de_bsp/de/disp_clk.o de_bsp/de/disp_combined.o de_bsp/de/disp_de.o de_bsp/de/disp_display.o\
							de_bsp/de/disp_event.o de_bsp/de/disp_hdmi.o de_bsp/de/disp_hwc.o de_bsp/de/disp_layer.o\
							de_bsp/de/disp_lcd.o de_bsp/de/disp_scaler.o de_bsp/de/disp_tv.o\
							de_bsp/de/disp_vga.o de_bsp/de/disp_video.o\
							de_bsp/iep/cmu/iep_cmu.o de_bsp/de/disp_iep.o\
							de_bsp/iep/drc/iep_drc.o de_bsp/iep/drc/iep_drc_ebios.o de_bsp/iep/drc/iep_wb_ebios.o\
							de_bsp/iep/deu/iep_deu.o de_bsp/iep/deu/iep_deu_ebios.o\
							de_bsp/de/disp_features.o de_bsp/de/disp_capture.o\
							#de_bsp/lcd/lcd0_panel_cfg.o de_bsp/lcd/lcd1_panel_cfg.o\

