# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_AW_THERMAL)	+= sunxi_thermal.o
obj-$(CONFIG_AW_CPUFREQ_CLAMP)	+= sunxi_cpufreq_clamp.o
obj-$(CONFIG_AW_THERMAL_CRITICAL_HANDLER) += sunxi_critical_handler.o
ccflags-y := -DDYNAMIC_DEBUG_MODULE
