copyfile generated/rogue/cache_bridge/client_cache_direct_bridge.c drivers/gpu/drm/img-rogue/client_cache_direct_bridge.c
copyfile generated/rogue/cache_bridge/server_cache_bridge.c drivers/gpu/drm/img-rogue/server_cache_bridge.c
copyfile generated/rogue/cmm_bridge/server_cmm_bridge.c drivers/gpu/drm/img-rogue/server_cmm_bridge.c
copyfile generated/rogue/devicememhistory_bridge/client_devicememhistory_direct_bridge.c drivers/gpu/drm/img-rogue/client_devicememhistory_direct_bridge.c
copyfile generated/rogue/devicememhistory_bridge/server_devicememhistory_bridge.c drivers/gpu/drm/img-rogue/server_devicememhistory_bridge.c
copyfile generated/rogue/di_bridge/server_di_bridge.c drivers/gpu/drm/img-rogue/server_di_bridge.c
copyfile generated/rogue/dmabuf_bridge/server_dmabuf_bridge.c drivers/gpu/drm/img-rogue/server_dmabuf_bridge.c
copyfile generated/rogue/htbuffer_bridge/client_htbuffer_direct_bridge.c drivers/gpu/drm/img-rogue/client_htbuffer_direct_bridge.c
copyfile generated/rogue/htbuffer_bridge/server_htbuffer_bridge.c drivers/gpu/drm/img-rogue/server_htbuffer_bridge.c
copyfile generated/rogue/mm_bridge/client_mm_direct_bridge.c drivers/gpu/drm/img-rogue/client_mm_direct_bridge.c
copyfile generated/rogue/mm_bridge/server_mm_bridge.c drivers/gpu/drm/img-rogue/server_mm_bridge.c
copyfile generated/rogue/mmextmem_bridge/server_mmextmem_bridge.c drivers/gpu/drm/img-rogue/server_mmextmem_bridge.c
copyfile generated/rogue/pvrtl_bridge/client_pvrtl_direct_bridge.c drivers/gpu/drm/img-rogue/client_pvrtl_direct_bridge.c
copyfile generated/rogue/pvrtl_bridge/server_pvrtl_bridge.c drivers/gpu/drm/img-rogue/server_pvrtl_bridge.c
copyfile generated/rogue/rgxbreakpoint_bridge/server_rgxbreakpoint_bridge.c drivers/gpu/drm/img-rogue/server_rgxbreakpoint_bridge.c
copyfile generated/rogue/rgxcmp_bridge/server_rgxcmp_bridge.c drivers/gpu/drm/img-rogue/server_rgxcmp_bridge.c
copyfile generated/rogue/rgxfwdbg_bridge/server_rgxfwdbg_bridge.c drivers/gpu/drm/img-rogue/server_rgxfwdbg_bridge.c
copyfile generated/rogue/rgxhwperf_bridge/server_rgxhwperf_bridge.c drivers/gpu/drm/img-rogue/server_rgxhwperf_bridge.c
copyfile generated/rogue/rgxkicksync_bridge/server_rgxkicksync_bridge.c drivers/gpu/drm/img-rogue/server_rgxkicksync_bridge.c
copyfile generated/rogue/rgxregconfig_bridge/server_rgxregconfig_bridge.c drivers/gpu/drm/img-rogue/server_rgxregconfig_bridge.c
copyfile generated/rogue/rgxta3d_bridge/server_rgxta3d_bridge.c drivers/gpu/drm/img-rogue/server_rgxta3d_bridge.c
copyfile generated/rogue/rgxtimerquery_bridge/server_rgxtimerquery_bridge.c drivers/gpu/drm/img-rogue/server_rgxtimerquery_bridge.c
copyfile generated/rogue/rgxtq2_bridge/server_rgxtq2_bridge.c drivers/gpu/drm/img-rogue/server_rgxtq2_bridge.c
copyfile generated/rogue/rgxtq_bridge/server_rgxtq_bridge.c drivers/gpu/drm/img-rogue/server_rgxtq_bridge.c
copyfile generated/rogue/ri_bridge/client_ri_direct_bridge.c drivers/gpu/drm/img-rogue/client_ri_direct_bridge.c
copyfile generated/rogue/ri_bridge/server_ri_bridge.c drivers/gpu/drm/img-rogue/server_ri_bridge.c
copyfile generated/rogue/srvcore_bridge/server_srvcore_bridge.c drivers/gpu/drm/img-rogue/server_srvcore_bridge.c
copyfile generated/rogue/sync_bridge/client_sync_direct_bridge.c drivers/gpu/drm/img-rogue/client_sync_direct_bridge.c
copyfile generated/rogue/sync_bridge/server_sync_bridge.c drivers/gpu/drm/img-rogue/server_sync_bridge.c
copyfile generated/rogue/synctracking_bridge/client_synctracking_direct_bridge.c drivers/gpu/drm/img-rogue/client_synctracking_direct_bridge.c
copyfile generated/rogue/synctracking_bridge/server_synctracking_bridge.c drivers/gpu/drm/img-rogue/server_synctracking_bridge.c
copyfile kernel/drivers/staging/imgtec/tc/drm_pdp_crtc.c drivers/gpu/drm/img-rogue/apollo/drm_pdp_crtc.c
copyfile kernel/drivers/staging/imgtec/tc/drm_pdp_debugfs.c drivers/gpu/drm/img-rogue/apollo/drm_pdp_debugfs.c
copyfile kernel/drivers/staging/imgtec/tc/drm_pdp_drv.c drivers/gpu/drm/img-rogue/apollo/drm_pdp_drv.c
copyfile kernel/drivers/staging/imgtec/tc/drm_pdp_dvi.c drivers/gpu/drm/img-rogue/apollo/drm_pdp_dvi.c
copyfile kernel/drivers/staging/imgtec/tc/drm_pdp_fb.c drivers/gpu/drm/img-rogue/apollo/drm_pdp_fb.c
copyfile kernel/drivers/staging/imgtec/tc/drm_pdp_gem.c drivers/gpu/drm/img-rogue/apollo/drm_pdp_gem.c
copyfile kernel/drivers/staging/imgtec/tc/drm_pdp_modeset.c drivers/gpu/drm/img-rogue/apollo/drm_pdp_modeset.c
copyfile kernel/drivers/staging/imgtec/tc/drm_pdp_plane.c drivers/gpu/drm/img-rogue/apollo/drm_pdp_plane.c
copyfile kernel/drivers/staging/imgtec/tc/drm_pdp_tmds.c drivers/gpu/drm/img-rogue/apollo/drm_pdp_tmds.c
copyfile kernel/drivers/staging/imgtec/tc/pdp_apollo.c drivers/gpu/drm/img-rogue/apollo/pdp_apollo.c
copyfile kernel/drivers/staging/imgtec/tc/pdp_odin.c drivers/gpu/drm/img-rogue/apollo/pdp_odin.c
copyfile kernel/drivers/staging/imgtec/tc/pdp_plato.c drivers/gpu/drm/img-rogue/apollo/pdp_plato.c
copyfile kernel/drivers/staging/imgtec/tc/tc_apollo.c drivers/gpu/drm/img-rogue/apollo/tc_apollo.c
copyfile kernel/drivers/staging/imgtec/tc/tc_drv.c drivers/gpu/drm/img-rogue/apollo/tc_drv.c
copyfile kernel/drivers/staging/imgtec/tc/tc_odin.c drivers/gpu/drm/img-rogue/apollo/tc_odin.c
copyfile services/server/common/cache_km.c drivers/gpu/drm/img-rogue/cache_km.c
copyfile services/server/common/connection_server.c drivers/gpu/drm/img-rogue/connection_server.c
copyfile services/server/common/debug_common.c drivers/gpu/drm/img-rogue/debug_common.c
copyfile services/server/common/devicemem_heapcfg.c drivers/gpu/drm/img-rogue/devicemem_heapcfg.c
copyfile services/server/common/devicemem_history_server.c drivers/gpu/drm/img-rogue/devicemem_history_server.c
copyfile services/server/common/devicemem_server.c drivers/gpu/drm/img-rogue/devicemem_server.c
copyfile services/server/common/di_impl_brg.c drivers/gpu/drm/img-rogue/di_impl_brg.c
copyfile services/server/common/di_server.c drivers/gpu/drm/img-rogue/di_server.c
copyfile services/server/common/handle.c drivers/gpu/drm/img-rogue/handle.c
copyfile services/server/common/htb_debug.c drivers/gpu/drm/img-rogue/htb_debug.c
copyfile services/server/common/htbserver.c drivers/gpu/drm/img-rogue/htbserver.c
copyfile services/server/common/info_page_km.c drivers/gpu/drm/img-rogue/info_page_km.c
copyfile services/server/common/lists.c drivers/gpu/drm/img-rogue/lists.c
copyfile services/server/common/mmu_common.c drivers/gpu/drm/img-rogue/mmu_common.c
copyfile services/server/common/physheap.c drivers/gpu/drm/img-rogue/physheap.c
copyfile services/server/common/physmem.c drivers/gpu/drm/img-rogue/physmem.c
copyfile services/server/common/physmem_extmem.c drivers/gpu/drm/img-rogue/physmem_extmem.c
copyfile services/server/common/physmem_hostmem.c drivers/gpu/drm/img-rogue/physmem_hostmem.c
copyfile services/server/common/physmem_lma.c drivers/gpu/drm/img-rogue/physmem_lma.c
copyfile services/server/common/physmem_osmem.c drivers/gpu/drm/img-rogue/physmem_osmem.c
copyfile services/server/common/physmem_ramem.c drivers/gpu/drm/img-rogue/physmem_ramem.c
copyfile services/server/common/pmr.c drivers/gpu/drm/img-rogue/pmr.c
copyfile services/server/common/power.c drivers/gpu/drm/img-rogue/power.c
copyfile services/server/common/process_stats.c drivers/gpu/drm/img-rogue/process_stats.c
copyfile services/server/common/pvr_notifier.c drivers/gpu/drm/img-rogue/pvr_notifier.c
copyfile services/server/common/pvrsrv.c drivers/gpu/drm/img-rogue/pvrsrv.c
copyfile services/server/common/pvrsrv_bridge_init.c drivers/gpu/drm/img-rogue/pvrsrv_bridge_init.c
copyfile services/server/common/pvrsrv_pool.c drivers/gpu/drm/img-rogue/pvrsrv_pool.c
copyfile services/server/common/ri_server.c drivers/gpu/drm/img-rogue/ri_server.c
copyfile services/server/common/srvcore.c drivers/gpu/drm/img-rogue/srvcore.c
copyfile services/server/common/sync_checkpoint.c drivers/gpu/drm/img-rogue/sync_checkpoint.c
copyfile services/server/common/sync_server.c drivers/gpu/drm/img-rogue/sync_server.c
copyfile services/server/common/tlintern.c drivers/gpu/drm/img-rogue/tlintern.c
copyfile services/server/common/tlserver.c drivers/gpu/drm/img-rogue/tlserver.c
copyfile services/server/common/tlstream.c drivers/gpu/drm/img-rogue/tlstream.c
copyfile services/server/common/vmm_pvz_client.c drivers/gpu/drm/img-rogue/vmm_pvz_client.c
copyfile services/server/common/vmm_pvz_server.c drivers/gpu/drm/img-rogue/vmm_pvz_server.c
copyfile services/server/common/vz_vmm_pvz.c drivers/gpu/drm/img-rogue/vz_vmm_pvz.c
copyfile services/server/common/vz_vmm_vm.c drivers/gpu/drm/img-rogue/vz_vmm_vm.c
copyfile services/server/devices/rgx_bridge_init.c drivers/gpu/drm/img-rogue/rgx_bridge_init.c
copyfile services/server/devices/rgxbreakpoint.c drivers/gpu/drm/img-rogue/rgxbreakpoint.c
copyfile services/server/devices/rgxbvnc.c drivers/gpu/drm/img-rogue/rgxbvnc.c
copyfile services/server/devices/rgxccb.c drivers/gpu/drm/img-rogue/rgxccb.c
copyfile services/server/devices/rgxcompute.c drivers/gpu/drm/img-rogue/rgxcompute.c
copyfile services/server/devices/rgxdebug_common.c drivers/gpu/drm/img-rogue/rgxdebug_common.c
copyfile services/server/devices/rgxfwcmnctx.c drivers/gpu/drm/img-rogue/rgxfwcmnctx.c
copyfile services/server/devices/rgxfwdbg.c drivers/gpu/drm/img-rogue/rgxfwdbg.c
copyfile services/server/devices/rgxfwimageutils.c drivers/gpu/drm/img-rogue/rgxfwimageutils.c
copyfile services/server/devices/rgxfwriscv.c drivers/gpu/drm/img-rogue/rgxfwriscv.c
copyfile services/server/devices/rgxfwtrace_strings.c drivers/gpu/drm/img-rogue/rgxfwtrace_strings.c
copyfile services/server/devices/rgxhwperf_common.c drivers/gpu/drm/img-rogue/rgxhwperf_common.c
copyfile services/server/devices/rgxkicksync.c drivers/gpu/drm/img-rogue/rgxkicksync.c
copyfile services/server/devices/rgxlayer_impl_common.c drivers/gpu/drm/img-rogue/rgxlayer_impl_common.c
copyfile services/server/devices/rgxmem.c drivers/gpu/drm/img-rogue/rgxmem.c
copyfile services/server/devices/rgxmmuinit.c drivers/gpu/drm/img-rogue/rgxmmuinit.c
copyfile services/server/devices/rgxpower.c drivers/gpu/drm/img-rogue/rgxpower.c
copyfile services/server/devices/rgxregconfig.c drivers/gpu/drm/img-rogue/rgxregconfig.c
copyfile services/server/devices/rgxshader.c drivers/gpu/drm/img-rogue/rgxshader.c
copyfile services/server/devices/rgxsyncutils.c drivers/gpu/drm/img-rogue/rgxsyncutils.c
copyfile services/server/devices/rgxtdmtransfer.c drivers/gpu/drm/img-rogue/rgxtdmtransfer.c
copyfile services/server/devices/rgxtimecorr.c drivers/gpu/drm/img-rogue/rgxtimecorr.c
copyfile services/server/devices/rgxtimerquery.c drivers/gpu/drm/img-rogue/rgxtimerquery.c
copyfile services/server/devices/rgxutils.c drivers/gpu/drm/img-rogue/rgxutils.c
copyfile services/server/devices/rogue/rgxdebug.c drivers/gpu/drm/img-rogue/rgxdebug.c
copyfile services/server/devices/rogue/rgxfwutils.c drivers/gpu/drm/img-rogue/rgxfwutils.c
copyfile services/server/devices/rogue/rgxhwperf.c drivers/gpu/drm/img-rogue/rgxhwperf.c
copyfile services/server/devices/rogue/rgxinit.c drivers/gpu/drm/img-rogue/rgxinit.c
copyfile services/server/devices/rogue/rgxlayer_impl.c drivers/gpu/drm/img-rogue/rgxlayer_impl.c
copyfile services/server/devices/rogue/rgxmipsmmuinit.c drivers/gpu/drm/img-rogue/rgxmipsmmuinit.c
copyfile services/server/devices/rogue/rgxmulticore.c drivers/gpu/drm/img-rogue/rgxmulticore.c
copyfile services/server/devices/rogue/rgxsrvinit.c drivers/gpu/drm/img-rogue/rgxsrvinit.c
copyfile services/server/devices/rogue/rgxstartstop.c drivers/gpu/drm/img-rogue/rgxstartstop.c
copyfile services/server/devices/rogue/rgxta3d.c drivers/gpu/drm/img-rogue/rgxta3d.c
copyfile services/server/devices/rogue/rgxtransfer.c drivers/gpu/drm/img-rogue/rgxtransfer.c
copyfile services/server/env/linux/allocmem.c drivers/gpu/drm/img-rogue/allocmem.c
copyfile services/server/env/linux/dkf_server.c drivers/gpu/drm/img-rogue/dkf_server.c
copyfile services/server/env/linux/event.c drivers/gpu/drm/img-rogue/event.c
copyfile services/server/env/linux/fwload.c drivers/gpu/drm/img-rogue/fwload.c
copyfile services/server/env/linux/handle_idr.c drivers/gpu/drm/img-rogue/handle_idr.c
copyfile services/server/env/linux/km_apphint.c drivers/gpu/drm/img-rogue/km_apphint.c
copyfile services/server/env/linux/module_common.c drivers/gpu/drm/img-rogue/module_common.c
copyfile services/server/env/linux/osconnection_server.c drivers/gpu/drm/img-rogue/osconnection_server.c
copyfile services/server/env/linux/osfunc.c drivers/gpu/drm/img-rogue/osfunc.c
copyfile services/server/env/linux/osmmap_stub.c drivers/gpu/drm/img-rogue/osmmap_stub.c
copyfile services/server/env/linux/physmem_dmabuf.c drivers/gpu/drm/img-rogue/physmem_dmabuf.c
copyfile services/server/env/linux/physmem_extmem_linux.c drivers/gpu/drm/img-rogue/physmem_extmem_linux.c
copyfile services/server/env/linux/physmem_osmem_linux.c drivers/gpu/drm/img-rogue/physmem_osmem_linux.c
copyfile services/server/env/linux/physmem_test.c drivers/gpu/drm/img-rogue/physmem_test.c
copyfile services/server/env/linux/pmr_env.c drivers/gpu/drm/img-rogue/pmr_env.c
copyfile services/server/env/linux/pmr_os.c drivers/gpu/drm/img-rogue/pmr_os.c
copyfile services/server/env/linux/pvr_bridge_k.c drivers/gpu/drm/img-rogue/pvr_bridge_k.c
copyfile services/server/env/linux/pvr_buffer_sync.c drivers/gpu/drm/img-rogue/pvr_buffer_sync.c
copyfile services/server/env/linux/pvr_counting_timeline.c drivers/gpu/drm/img-rogue/pvr_counting_timeline.c
copyfile services/server/env/linux/pvr_debug.c drivers/gpu/drm/img-rogue/pvr_debug.c
copyfile services/server/env/linux/pvr_debugfs.c drivers/gpu/drm/img-rogue/pvr_debugfs.c
copyfile services/server/env/linux/pvr_drm.c drivers/gpu/drm/img-rogue/pvr_drm.c
copyfile services/server/env/linux/pvr_export_fence.c drivers/gpu/drm/img-rogue/pvr_export_fence.c
copyfile services/server/env/linux/pvr_fence.c drivers/gpu/drm/img-rogue/pvr_fence.c
copyfile services/server/env/linux/pvr_gputrace.c drivers/gpu/drm/img-rogue/pvr_gputrace.c
copyfile services/server/env/linux/pvr_platform_drv.c drivers/gpu/drm/img-rogue/pvr_platform_drv.c
copyfile services/server/env/linux/pvr_sw_fence.c drivers/gpu/drm/img-rogue/pvr_sw_fence.c
copyfile services/server/env/linux/pvr_sync_file.c drivers/gpu/drm/img-rogue/pvr_sync_file.c
copyfile services/server/env/linux/pvr_sync_ioctl_common.c drivers/gpu/drm/img-rogue/pvr_sync_ioctl_common.c
copyfile services/server/env/linux/pvr_sync_ioctl_drm.c drivers/gpu/drm/img-rogue/pvr_sync_ioctl_drm.c
copyfile services/shared/common/devicemem.c drivers/gpu/drm/img-rogue/devicemem.c
copyfile services/shared/common/devicemem_utils.c drivers/gpu/drm/img-rogue/devicemem_utils.c
copyfile services/shared/common/hash.c drivers/gpu/drm/img-rogue/hash.c
copyfile services/shared/common/htbuffer.c drivers/gpu/drm/img-rogue/htbuffer.c
copyfile services/shared/common/mem_utils.c drivers/gpu/drm/img-rogue/mem_utils.c
copyfile services/shared/common/pvrsrv_error.c drivers/gpu/drm/img-rogue/pvrsrv_error.c
copyfile services/shared/common/ra.c drivers/gpu/drm/img-rogue/ra.c
copyfile services/shared/common/sync.c drivers/gpu/drm/img-rogue/sync.c
copyfile services/shared/common/tlclient.c drivers/gpu/drm/img-rogue/tlclient.c
copyfile services/shared/common/uniq_key_splay_tree.c drivers/gpu/drm/img-rogue/uniq_key_splay_tree.c
copyfile services/shared/devices/rogue/rgx_hwperf_table.c drivers/gpu/drm/img-rogue/rgx_hwperf_table.c
copyfile services/system/common/env/linux/interrupt_support.c drivers/gpu/drm/img-rogue/interrupt_support.c
copyfile services/system/common/env/linux/pci_support.c drivers/gpu/drm/img-rogue/pci_support.c
copyfile services/system/common/sysconfig_cmn.c drivers/gpu/drm/img-rogue/sysconfig_cmn.c
copyfile services/system/rogue/common/env/linux/dma_support.c drivers/gpu/drm/img-rogue/dma_support.c
copyfile services/system/rogue/common/vmm_type_stub.c drivers/gpu/drm/img-rogue/vmm_type_stub.c
copyfile services/system/rogue/rgx_linux_tc/sysconfig.c drivers/gpu/drm/img-rogue/apollo/sysconfig.c
copyfile services/server/env/linux/osfunc_x86.c drivers/gpu/drm/img-rogue/osfunc_x86.c
copyfile services/server/env/linux/osfunc_arm.c drivers/gpu/drm/img-rogue/osfunc_arm.c
copyfile services/server/env/linux/osfunc_arm64.c drivers/gpu/drm/img-rogue/osfunc_arm64.c
copyfile services/server/env/linux/osfunc_riscv.c drivers/gpu/drm/img-rogue/osfunc_riscv.c
copyfile services/server/env/linux/trace_events.c drivers/gpu/drm/img-rogue/trace_events.c
copyfile generated/rogue/cache_bridge/client_cache_bridge.h drivers/gpu/drm/img-rogue/client_cache_bridge.h
copyfile generated/rogue/cache_bridge/common_cache_bridge.h drivers/gpu/drm/img-rogue/common_cache_bridge.h
copyfile generated/rogue/cmm_bridge/common_cmm_bridge.h drivers/gpu/drm/img-rogue/common_cmm_bridge.h
copyfile generated/rogue/devicememhistory_bridge/client_devicememhistory_bridge.h drivers/gpu/drm/img-rogue/client_devicememhistory_bridge.h
copyfile generated/rogue/devicememhistory_bridge/common_devicememhistory_bridge.h drivers/gpu/drm/img-rogue/common_devicememhistory_bridge.h
copyfile generated/rogue/di_bridge/common_di_bridge.h drivers/gpu/drm/img-rogue/common_di_bridge.h
copyfile generated/rogue/dmabuf_bridge/common_dmabuf_bridge.h drivers/gpu/drm/img-rogue/common_dmabuf_bridge.h
copyfile generated/rogue/htbuffer_bridge/client_htbuffer_bridge.h drivers/gpu/drm/img-rogue/client_htbuffer_bridge.h
copyfile generated/rogue/htbuffer_bridge/common_htbuffer_bridge.h drivers/gpu/drm/img-rogue/common_htbuffer_bridge.h
copyfile generated/rogue/mm_bridge/client_mm_bridge.h drivers/gpu/drm/img-rogue/client_mm_bridge.h
copyfile generated/rogue/mm_bridge/common_mm_bridge.h drivers/gpu/drm/img-rogue/common_mm_bridge.h
copyfile generated/rogue/mmextmem_bridge/common_mmextmem_bridge.h drivers/gpu/drm/img-rogue/common_mmextmem_bridge.h
copyfile generated/rogue/pvrtl_bridge/client_pvrtl_bridge.h drivers/gpu/drm/img-rogue/client_pvrtl_bridge.h
copyfile generated/rogue/pvrtl_bridge/common_pvrtl_bridge.h drivers/gpu/drm/img-rogue/common_pvrtl_bridge.h
copyfile generated/rogue/rgxbreakpoint_bridge/common_rgxbreakpoint_bridge.h drivers/gpu/drm/img-rogue/common_rgxbreakpoint_bridge.h
copyfile generated/rogue/rgxcmp_bridge/common_rgxcmp_bridge.h drivers/gpu/drm/img-rogue/common_rgxcmp_bridge.h
copyfile generated/rogue/rgxfwdbg_bridge/common_rgxfwdbg_bridge.h drivers/gpu/drm/img-rogue/common_rgxfwdbg_bridge.h
copyfile generated/rogue/rgxhwperf_bridge/common_rgxhwperf_bridge.h drivers/gpu/drm/img-rogue/common_rgxhwperf_bridge.h
copyfile generated/rogue/rgxkicksync_bridge/common_rgxkicksync_bridge.h drivers/gpu/drm/img-rogue/common_rgxkicksync_bridge.h
copyfile generated/rogue/rgxregconfig_bridge/common_rgxregconfig_bridge.h drivers/gpu/drm/img-rogue/common_rgxregconfig_bridge.h
copyfile generated/rogue/rgxta3d_bridge/common_rgxta3d_bridge.h drivers/gpu/drm/img-rogue/common_rgxta3d_bridge.h
copyfile generated/rogue/rgxtimerquery_bridge/common_rgxtimerquery_bridge.h drivers/gpu/drm/img-rogue/common_rgxtimerquery_bridge.h
copyfile generated/rogue/rgxtq2_bridge/common_rgxtq2_bridge.h drivers/gpu/drm/img-rogue/common_rgxtq2_bridge.h
copyfile generated/rogue/rgxtq_bridge/common_rgxtq_bridge.h drivers/gpu/drm/img-rogue/common_rgxtq_bridge.h
copyfile generated/rogue/ri_bridge/client_ri_bridge.h drivers/gpu/drm/img-rogue/client_ri_bridge.h
copyfile generated/rogue/ri_bridge/common_ri_bridge.h drivers/gpu/drm/img-rogue/common_ri_bridge.h
copyfile generated/rogue/srvcore_bridge/common_srvcore_bridge.h drivers/gpu/drm/img-rogue/common_srvcore_bridge.h
copyfile generated/rogue/sync_bridge/client_sync_bridge.h drivers/gpu/drm/img-rogue/client_sync_bridge.h
copyfile generated/rogue/sync_bridge/common_sync_bridge.h drivers/gpu/drm/img-rogue/common_sync_bridge.h
copyfile generated/rogue/synctracking_bridge/client_synctracking_bridge.h drivers/gpu/drm/img-rogue/client_synctracking_bridge.h
copyfile generated/rogue/synctracking_bridge/common_synctracking_bridge.h drivers/gpu/drm/img-rogue/common_synctracking_bridge.h
copyfile hwdefs/rogue/km/configs/rgxconfig_km_1.V.4.5.h drivers/gpu/drm/img-rogue/configs/rgxconfig_km_1.V.4.5.h
copyfile hwdefs/rogue/km/cores/rgxcore_km_1.82.4.5.h drivers/gpu/drm/img-rogue/cores/rgxcore_km_1.82.4.5.h
copyfile hwdefs/rogue/km/rgx_bvnc_defs_km.h drivers/gpu/drm/img-rogue/km/rgx_bvnc_defs_km.h
copyfile hwdefs/rogue/km/rgx_bvnc_table_km.h drivers/gpu/drm/img-rogue/km/rgx_bvnc_table_km.h
copyfile hwdefs/rogue/km/rgx_cr_defs_km.h drivers/gpu/drm/img-rogue/km/rgx_cr_defs_km.h
copyfile hwdefs/rogue/km/rgxdefs_km.h drivers/gpu/drm/img-rogue/km/rgxdefs_km.h
copyfile hwdefs/rogue/km/rgxmhdefs_km.h drivers/gpu/drm/img-rogue/km/rgxmhdefs_km.h
copyfile hwdefs/rogue/km/rgxmmudefs_km.h drivers/gpu/drm/img-rogue/km/rgxmmudefs_km.h
copyfile include/cache_ops.h drivers/gpu/drm/img-rogue/cache_ops.h
copyfile include/devicemem_typedefs.h drivers/gpu/drm/img-rogue/devicemem_typedefs.h
copyfile include/dllist.h drivers/gpu/drm/img-rogue/dllist.h
copyfile include/drm/pdp_drm.h drivers/gpu/drm/img-rogue/pdp_drm.h
copyfile include/drm/pvr_drm.h drivers/gpu/drm/img-rogue/pvr_drm.h
copyfile include/img_3dtypes.h drivers/gpu/drm/img-rogue/img_3dtypes.h
copyfile include/img_defs.h drivers/gpu/drm/img-rogue/img_defs.h
copyfile include/img_elf.h drivers/gpu/drm/img-rogue/img_elf.h
copyfile include/img_types.h drivers/gpu/drm/img-rogue/img_types.h
copyfile include/kernel_types.h drivers/gpu/drm/img-rogue/kernel_types.h
copyfile include/linux_sw_sync.h drivers/gpu/drm/img-rogue/linux_sw_sync.h
copyfile include/lock_types.h drivers/gpu/drm/img-rogue/lock_types.h
copyfile include/log2.h drivers/gpu/drm/img-rogue/log2.h
copyfile include/multicore_defs.h drivers/gpu/drm/img-rogue/multicore_defs.h
copyfile include/osfunc_common.h drivers/gpu/drm/img-rogue/osfunc_common.h
copyfile include/pdumpdefs.h drivers/gpu/drm/img-rogue/pdumpdefs.h
copyfile include/pdumpdesc.h drivers/gpu/drm/img-rogue/pdumpdesc.h
copyfile include/public/powervr/buffer_attribs.h drivers/gpu/drm/img-rogue/powervr/buffer_attribs.h
copyfile include/public/powervr/img_drm_fourcc.h drivers/gpu/drm/img-rogue/powervr/img_drm_fourcc.h
copyfile include/public/powervr/mem_types.h drivers/gpu/drm/img-rogue/powervr/mem_types.h
copyfile include/public/powervr/pvrsrv_sync_ext.h drivers/gpu/drm/img-rogue/powervr/pvrsrv_sync_ext.h
copyfile include/pvr_buffer_sync_shared.h drivers/gpu/drm/img-rogue/pvr_buffer_sync_shared.h
copyfile include/pvr_debug.h drivers/gpu/drm/img-rogue/pvr_debug.h
copyfile include/pvr_fd_sync_kernel.h drivers/gpu/drm/img-rogue/pvr_fd_sync_kernel.h
copyfile include/pvr_intrinsics.h drivers/gpu/drm/img-rogue/pvr_intrinsics.h
copyfile include/pvrmodule.h drivers/gpu/drm/img-rogue/pvrmodule.h
copyfile include/pvrsrv_device_types.h drivers/gpu/drm/img-rogue/pvrsrv_device_types.h
copyfile include/pvrsrv_devvar.h drivers/gpu/drm/img-rogue/pvrsrv_devvar.h
copyfile include/pvrsrv_error.h drivers/gpu/drm/img-rogue/pvrsrv_error.h
copyfile include/pvrsrv_errors.h drivers/gpu/drm/img-rogue/pvrsrv_errors.h
copyfile include/pvrsrv_memalloc_physheap.h drivers/gpu/drm/img-rogue/pvrsrv_memalloc_physheap.h
copyfile include/pvrsrv_memallocflags.h drivers/gpu/drm/img-rogue/pvrsrv_memallocflags.h
copyfile include/pvrsrv_memallocflags_internal.h drivers/gpu/drm/img-rogue/pvrsrv_memallocflags_internal.h
copyfile include/pvrsrv_sync_km.h drivers/gpu/drm/img-rogue/pvrsrv_sync_km.h
copyfile include/pvrsrv_tlcommon.h drivers/gpu/drm/img-rogue/pvrsrv_tlcommon.h
copyfile include/pvrsrv_tlstreams.h drivers/gpu/drm/img-rogue/pvrsrv_tlstreams.h
copyfile include/pvrversion.h drivers/gpu/drm/img-rogue/pvrversion.h
copyfile include/rgx_common.h drivers/gpu/drm/img-rogue/rgx_common.h
copyfile include/rgx_common_asserts.h drivers/gpu/drm/img-rogue/rgx_common_asserts.h
copyfile include/rgx_compat_bvnc.h drivers/gpu/drm/img-rogue/rgx_compat_bvnc.h
copyfile include/rgx_fwif_resetframework.h drivers/gpu/drm/img-rogue/rgx_fwif_resetframework.h
copyfile include/rgx_fwif_sf.h drivers/gpu/drm/img-rogue/rgx_fwif_sf.h
copyfile include/rgx_heap_firmware.h drivers/gpu/drm/img-rogue/rgx_heap_firmware.h
copyfile include/rgx_hwperf_common.h drivers/gpu/drm/img-rogue/rgx_hwperf_common.h
copyfile include/rgx_meta.h drivers/gpu/drm/img-rogue/rgx_meta.h
copyfile include/rgx_mips.h drivers/gpu/drm/img-rogue/rgx_mips.h
copyfile include/rgx_riscv.h drivers/gpu/drm/img-rogue/rgx_riscv.h
copyfile include/rgxfw_log_helper.h drivers/gpu/drm/img-rogue/rgxfw_log_helper.h
copyfile include/ri_typedefs.h drivers/gpu/drm/img-rogue/ri_typedefs.h
copyfile include/rogue/rgx_fwif_alignchecks.h drivers/gpu/drm/img-rogue/rgx_fwif_alignchecks.h
copyfile include/rogue/rgx_fwif_hwperf.h drivers/gpu/drm/img-rogue/rgx_fwif_hwperf.h
copyfile include/rogue/rgx_fwif_km.h drivers/gpu/drm/img-rogue/rgx_fwif_km.h
copyfile include/rogue/rgx_fwif_shared.h drivers/gpu/drm/img-rogue/rgx_fwif_shared.h
copyfile include/rogue/rgx_heaps.h drivers/gpu/drm/img-rogue/rgx_heaps.h
copyfile include/rogue/rgx_hwperf.h drivers/gpu/drm/img-rogue/rgx_hwperf.h
copyfile include/rogue/rgx_options.h drivers/gpu/drm/img-rogue/rgx_options.h
copyfile include/rogue/rgxheapconfig.h drivers/gpu/drm/img-rogue/rgxheapconfig.h
copyfile include/rogue/rgxheapconfig_65273.h drivers/gpu/drm/img-rogue/rgxheapconfig_65273.h
copyfile include/rogue/system/rgx_tc/tc_clocks.h drivers/gpu/drm/img-rogue/apollo/tc_clocks.h
copyfile include/services_km.h drivers/gpu/drm/img-rogue/services_km.h
copyfile include/servicesext.h drivers/gpu/drm/img-rogue/servicesext.h
copyfile include/sync_checkpoint_external.h drivers/gpu/drm/img-rogue/sync_checkpoint_external.h
copyfile include/sync_prim_internal.h drivers/gpu/drm/img-rogue/sync_prim_internal.h
copyfile include/system/rgx_tc/apollo_regs.h drivers/gpu/drm/img-rogue/apollo/apollo_regs.h
copyfile include/system/rgx_tc/bonnie_tcf.h drivers/gpu/drm/img-rogue/apollo/bonnie_tcf.h
copyfile include/system/rgx_tc/odin_defs.h drivers/gpu/drm/img-rogue/apollo/odin_defs.h
copyfile include/system/rgx_tc/odin_pdp_regs.h drivers/gpu/drm/img-rogue/apollo/odin_pdp_regs.h
copyfile include/system/rgx_tc/odin_regs.h drivers/gpu/drm/img-rogue/apollo/odin_regs.h
copyfile include/system/rgx_tc/orion_defs.h drivers/gpu/drm/img-rogue/apollo/orion_defs.h
copyfile include/system/rgx_tc/orion_regs.h drivers/gpu/drm/img-rogue/apollo/orion_regs.h
copyfile include/system/rgx_tc/pdp_regs.h drivers/gpu/drm/img-rogue/apollo/pdp_regs.h
copyfile include/system/rgx_tc/pfim_defs.h drivers/gpu/drm/img-rogue/apollo/pfim_defs.h
copyfile include/system/rgx_tc/pfim_regs.h drivers/gpu/drm/img-rogue/apollo/pfim_regs.h
copyfile include/system/rgx_tc/tcf_clk_ctrl.h drivers/gpu/drm/img-rogue/apollo/tcf_clk_ctrl.h
copyfile include/system/rgx_tc/tcf_pll.h drivers/gpu/drm/img-rogue/apollo/tcf_pll.h
copyfile include/system/rgx_tc/tcf_rgbpdp_regs.h drivers/gpu/drm/img-rogue/apollo/tcf_rgbpdp_regs.h
copyfile kernel/drivers/staging/imgtec/kernel_compatibility.h drivers/gpu/drm/img-rogue/kernel_compatibility.h
copyfile kernel/drivers/staging/imgtec/kernel_nospec.h drivers/gpu/drm/img-rogue/kernel_nospec.h
copyfile kernel/drivers/staging/imgtec/plato/pdp2_mmu_regs.h drivers/gpu/drm/img-rogue/pdp2_mmu_regs.h
copyfile kernel/drivers/staging/imgtec/plato/pdp2_regs.h drivers/gpu/drm/img-rogue/pdp2_regs.h
copyfile kernel/drivers/staging/imgtec/plato/plato_drv.h drivers/gpu/drm/img-rogue/plato_drv.h
copyfile kernel/drivers/staging/imgtec/pvr_dma_resv.h drivers/gpu/drm/img-rogue/pvr_dma_resv.h
copyfile kernel/drivers/staging/imgtec/pvr_linux_fence.h drivers/gpu/drm/img-rogue/pvr_linux_fence.h
copyfile kernel/drivers/staging/imgtec/pvr_vmap.h drivers/gpu/drm/img-rogue/pvr_vmap.h
copyfile kernel/drivers/staging/imgtec/tc/drm_pdp_drv.h drivers/gpu/drm/img-rogue/apollo/drm_pdp_drv.h
copyfile kernel/drivers/staging/imgtec/tc/drm_pdp_gem.h drivers/gpu/drm/img-rogue/apollo/drm_pdp_gem.h
copyfile kernel/drivers/staging/imgtec/tc/pdp_apollo.h drivers/gpu/drm/img-rogue/apollo/pdp_apollo.h
copyfile kernel/drivers/staging/imgtec/tc/pdp_common.h drivers/gpu/drm/img-rogue/apollo/pdp_common.h
copyfile kernel/drivers/staging/imgtec/tc/pdp_odin.h drivers/gpu/drm/img-rogue/apollo/pdp_odin.h
copyfile kernel/drivers/staging/imgtec/tc/pdp_plato.h drivers/gpu/drm/img-rogue/apollo/pdp_plato.h
copyfile kernel/drivers/staging/imgtec/tc/tc_apollo.h drivers/gpu/drm/img-rogue/apollo/tc_apollo.h
copyfile kernel/drivers/staging/imgtec/tc/tc_drv.h drivers/gpu/drm/img-rogue/apollo/tc_drv.h
copyfile kernel/drivers/staging/imgtec/tc/tc_drv_internal.h drivers/gpu/drm/img-rogue/apollo/tc_drv_internal.h
copyfile kernel/drivers/staging/imgtec/tc/tc_odin.h drivers/gpu/drm/img-rogue/apollo/tc_odin.h
copyfile kernel/drivers/staging/imgtec/tc/tc_odin_common_regs.h drivers/gpu/drm/img-rogue/apollo/tc_odin_common_regs.h
copyfile services/include/htbuffer_sf.h drivers/gpu/drm/img-rogue/htbuffer_sf.h
copyfile services/include/htbuffer_types.h drivers/gpu/drm/img-rogue/htbuffer_types.h
copyfile services/include/img_types_check.h drivers/gpu/drm/img-rogue/img_types_check.h
copyfile services/include/info_page_client.h drivers/gpu/drm/img-rogue/info_page_client.h
copyfile services/include/info_page_defs.h drivers/gpu/drm/img-rogue/info_page_defs.h
copyfile services/include/km_apphint_defs_common.h drivers/gpu/drm/img-rogue/km_apphint_defs_common.h
copyfile services/include/os_cpu_cache.h drivers/gpu/drm/img-rogue/os_cpu_cache.h
copyfile services/include/pdump.h drivers/gpu/drm/img-rogue/pdump.h
copyfile services/include/physheap.h drivers/gpu/drm/img-rogue/physheap.h
copyfile services/include/physheap_config.h drivers/gpu/drm/img-rogue/physheap_config.h
copyfile services/include/pvr_bridge.h drivers/gpu/drm/img-rogue/pvr_bridge.h
copyfile services/include/pvr_dicommon.h drivers/gpu/drm/img-rogue/pvr_dicommon.h
copyfile services/include/pvr_ricommon.h drivers/gpu/drm/img-rogue/pvr_ricommon.h
copyfile services/include/rgx_bridge.h drivers/gpu/drm/img-rogue/rgx_bridge.h
copyfile services/include/rgx_fw_info.h drivers/gpu/drm/img-rogue/rgx_fw_info.h
copyfile services/include/rgx_memallocflags.h drivers/gpu/drm/img-rogue/rgx_memallocflags.h
copyfile services/include/rgx_pdump_panics.h drivers/gpu/drm/img-rogue/rgx_pdump_panics.h
copyfile services/include/rgx_tq_shared.h drivers/gpu/drm/img-rogue/rgx_tq_shared.h
copyfile services/include/rgxtransfer_shader.h drivers/gpu/drm/img-rogue/rgxtransfer_shader.h
copyfile services/include/rogue/km_apphint_defs.h drivers/gpu/drm/img-rogue/km_apphint_defs.h
copyfile services/include/rogue/rgxapi_km.h drivers/gpu/drm/img-rogue/rgxapi_km.h
copyfile services/include/sync_checkpoint_internal.h drivers/gpu/drm/img-rogue/sync_checkpoint_internal.h
copyfile services/server/common/di_impl_brg.h drivers/gpu/drm/img-rogue/di_impl_brg.h
copyfile services/server/common/di_impl_brg_intern.h drivers/gpu/drm/img-rogue/di_impl_brg_intern.h
copyfile services/server/common/htb_debug.h drivers/gpu/drm/img-rogue/htb_debug.h
copyfile services/server/devices/rgx_bridge_init.h drivers/gpu/drm/img-rogue/rgx_bridge_init.h
copyfile services/server/devices/rgx_heaps_server.h drivers/gpu/drm/img-rogue/rgx_heaps_server.h
copyfile services/server/devices/rgxbreakpoint.h drivers/gpu/drm/img-rogue/rgxbreakpoint.h
copyfile services/server/devices/rgxbvnc.h drivers/gpu/drm/img-rogue/rgxbvnc.h
copyfile services/server/devices/rgxccb.h drivers/gpu/drm/img-rogue/rgxccb.h
copyfile services/server/devices/rgxcompute.h drivers/gpu/drm/img-rogue/rgxcompute.h
copyfile services/server/devices/rgxdebug_common.h drivers/gpu/drm/img-rogue/rgxdebug_common.h
copyfile services/server/devices/rgxfwcmnctx.h drivers/gpu/drm/img-rogue/rgxfwcmnctx.h
copyfile services/server/devices/rgxfwdbg.h drivers/gpu/drm/img-rogue/rgxfwdbg.h
copyfile services/server/devices/rgxfwimageutils.h drivers/gpu/drm/img-rogue/rgxfwimageutils.h
copyfile services/server/devices/rgxfwmemctx.h drivers/gpu/drm/img-rogue/rgxfwmemctx.h
copyfile services/server/devices/rgxfwriscv.h drivers/gpu/drm/img-rogue/rgxfwriscv.h
copyfile services/server/devices/rgxfwutils.h drivers/gpu/drm/img-rogue/rgxfwutils.h
copyfile services/server/devices/rgxhwperf.h drivers/gpu/drm/img-rogue/rgxhwperf.h
copyfile services/server/devices/rgxhwperf_common.h drivers/gpu/drm/img-rogue/rgxhwperf_common.h
copyfile services/server/devices/rgxinit.h drivers/gpu/drm/img-rogue/rgxinit.h
copyfile services/server/devices/rgxinit_apphints.h drivers/gpu/drm/img-rogue/rgxinit_apphints.h
copyfile services/server/devices/rgxkicksync.h drivers/gpu/drm/img-rogue/rgxkicksync.h
copyfile services/server/devices/rgxlayer.h drivers/gpu/drm/img-rogue/rgxlayer.h
copyfile services/server/devices/rgxlayer_impl.h drivers/gpu/drm/img-rogue/rgxlayer_impl.h
copyfile services/server/devices/rgxmem.h drivers/gpu/drm/img-rogue/rgxmem.h
copyfile services/server/devices/rgxmmuinit.h drivers/gpu/drm/img-rogue/rgxmmuinit.h
copyfile services/server/devices/rgxmulticore.h drivers/gpu/drm/img-rogue/rgxmulticore.h
copyfile services/server/devices/rgxpower.h drivers/gpu/drm/img-rogue/rgxpower.h
copyfile services/server/devices/rgxregconfig.h drivers/gpu/drm/img-rogue/rgxregconfig.h
copyfile services/server/devices/rgxshader.h drivers/gpu/drm/img-rogue/rgxshader.h
copyfile services/server/devices/rgxstartstop.h drivers/gpu/drm/img-rogue/rgxstartstop.h
copyfile services/server/devices/rgxsyncutils.h drivers/gpu/drm/img-rogue/rgxsyncutils.h
copyfile services/server/devices/rgxtdmtransfer.h drivers/gpu/drm/img-rogue/rgxtdmtransfer.h
copyfile services/server/devices/rgxtimecorr.h drivers/gpu/drm/img-rogue/rgxtimecorr.h
copyfile services/server/devices/rgxtimerquery.h drivers/gpu/drm/img-rogue/rgxtimerquery.h
copyfile services/server/devices/rgxutils.h drivers/gpu/drm/img-rogue/rgxutils.h
copyfile services/server/devices/rogue/rgxdevice.h drivers/gpu/drm/img-rogue/rgxdevice.h
copyfile services/server/devices/rogue/rgxmipsmmuinit.h drivers/gpu/drm/img-rogue/rgxmipsmmuinit.h
copyfile services/server/devices/rogue/rgxta3d.h drivers/gpu/drm/img-rogue/rgxta3d.h
copyfile services/server/devices/rogue/rgxtransfer.h drivers/gpu/drm/img-rogue/rgxtransfer.h
copyfile services/server/env/linux/dkf_server.h drivers/gpu/drm/img-rogue/dkf_server.h
copyfile services/server/env/linux/env_connection.h drivers/gpu/drm/img-rogue/env_connection.h
copyfile services/server/env/linux/event.h drivers/gpu/drm/img-rogue/event.h
copyfile services/server/env/linux/km_apphint.h drivers/gpu/drm/img-rogue/km_apphint.h
copyfile services/server/env/linux/linkage.h drivers/gpu/drm/img-rogue/linkage.h
copyfile services/server/env/linux/module_common.h drivers/gpu/drm/img-rogue/module_common.h
copyfile services/server/env/linux/physmem_dmabuf_internal.h drivers/gpu/drm/img-rogue/physmem_dmabuf_internal.h
copyfile services/server/env/linux/physmem_extmem_wrap.h drivers/gpu/drm/img-rogue/physmem_extmem_wrap.h
copyfile services/server/env/linux/physmem_osmem_linux.h drivers/gpu/drm/img-rogue/physmem_osmem_linux.h
copyfile services/server/env/linux/physmem_test.h drivers/gpu/drm/img-rogue/physmem_test.h
copyfile services/server/env/linux/pmr_env.h drivers/gpu/drm/img-rogue/pmr_env.h
copyfile services/server/env/linux/private_data.h drivers/gpu/drm/img-rogue/private_data.h
copyfile services/server/env/linux/pvr_bridge_k.h drivers/gpu/drm/img-rogue/pvr_bridge_k.h
copyfile services/server/env/linux/pvr_buffer_sync.h drivers/gpu/drm/img-rogue/pvr_buffer_sync.h
copyfile services/server/env/linux/pvr_counting_timeline.h drivers/gpu/drm/img-rogue/pvr_counting_timeline.h
copyfile services/server/env/linux/pvr_debugfs.h drivers/gpu/drm/img-rogue/pvr_debugfs.h
copyfile services/server/env/linux/pvr_drv.h drivers/gpu/drm/img-rogue/pvr_drv.h
copyfile services/server/env/linux/pvr_export_fence.h drivers/gpu/drm/img-rogue/pvr_export_fence.h
copyfile services/server/env/linux/pvr_fence.h drivers/gpu/drm/img-rogue/pvr_fence.h
copyfile services/server/env/linux/pvr_fence_trace.h drivers/gpu/drm/img-rogue/pvr_fence_trace.h
copyfile services/server/env/linux/pvr_ion_stats.h drivers/gpu/drm/img-rogue/pvr_ion_stats.h
copyfile services/server/env/linux/pvr_procfs.h drivers/gpu/drm/img-rogue/pvr_procfs.h
copyfile services/server/env/linux/pvr_sw_fence.h drivers/gpu/drm/img-rogue/pvr_sw_fence.h
copyfile services/server/env/linux/pvr_sync.h drivers/gpu/drm/img-rogue/pvr_sync.h
copyfile services/server/env/linux/pvr_sync_api.h drivers/gpu/drm/img-rogue/pvr_sync_api.h
copyfile services/server/env/linux/pvr_sync_ioctl_common.h drivers/gpu/drm/img-rogue/pvr_sync_ioctl_common.h
copyfile services/server/env/linux/pvr_sync_ioctl_drm.h drivers/gpu/drm/img-rogue/pvr_sync_ioctl_drm.h
copyfile services/server/env/linux/pvr_uaccess.h drivers/gpu/drm/img-rogue/pvr_uaccess.h
copyfile services/server/env/linux/rogue_trace_events.h drivers/gpu/drm/img-rogue/rogue_trace_events.h
copyfile services/server/env/linux/services_kernel_client.h drivers/gpu/drm/img-rogue/services_kernel_client.h
copyfile services/server/env/linux/trace_events.h drivers/gpu/drm/img-rogue/trace_events.h
copyfile services/server/include/cache_km.h drivers/gpu/drm/img-rogue/cache_km.h
copyfile services/server/include/connection_server.h drivers/gpu/drm/img-rogue/connection_server.h
copyfile services/server/include/debug_common.h drivers/gpu/drm/img-rogue/debug_common.h
copyfile services/server/include/device.h drivers/gpu/drm/img-rogue/device.h
copyfile services/server/include/devicemem_heapcfg.h drivers/gpu/drm/img-rogue/devicemem_heapcfg.h
copyfile services/server/include/devicemem_history_server.h drivers/gpu/drm/img-rogue/devicemem_history_server.h
copyfile services/server/include/devicemem_server.h drivers/gpu/drm/img-rogue/devicemem_server.h
copyfile services/server/include/devicemem_server_utils.h drivers/gpu/drm/img-rogue/devicemem_server_utils.h
copyfile services/server/include/di_common.h drivers/gpu/drm/img-rogue/di_common.h
copyfile services/server/include/di_server.h drivers/gpu/drm/img-rogue/di_server.h
copyfile services/server/include/dkp_impl.h drivers/gpu/drm/img-rogue/dkp_impl.h
copyfile services/server/include/dma_km.h drivers/gpu/drm/img-rogue/dma_km.h
copyfile services/server/include/fwload.h drivers/gpu/drm/img-rogue/fwload.h
copyfile services/server/include/fwtrace_string.h drivers/gpu/drm/img-rogue/fwtrace_string.h
copyfile services/server/include/handle.h drivers/gpu/drm/img-rogue/handle.h
copyfile services/server/include/handle_impl.h drivers/gpu/drm/img-rogue/handle_impl.h
copyfile services/server/include/handle_types.h drivers/gpu/drm/img-rogue/handle_types.h
copyfile services/server/include/htbserver.h drivers/gpu/drm/img-rogue/htbserver.h
copyfile services/server/include/info_page.h drivers/gpu/drm/img-rogue/info_page.h
copyfile services/server/include/lists.h drivers/gpu/drm/img-rogue/lists.h
copyfile services/server/include/mmu_common.h drivers/gpu/drm/img-rogue/mmu_common.h
copyfile services/server/include/opaque_types.h drivers/gpu/drm/img-rogue/opaque_types.h
copyfile services/server/include/os_apphint.h drivers/gpu/drm/img-rogue/os_apphint.h
copyfile services/server/include/osconnection_server.h drivers/gpu/drm/img-rogue/osconnection_server.h
copyfile services/server/include/osdi_impl.h drivers/gpu/drm/img-rogue/osdi_impl.h
copyfile services/server/include/osfunc.h drivers/gpu/drm/img-rogue/osfunc.h
copyfile services/server/include/ospvr_gputrace.h drivers/gpu/drm/img-rogue/ospvr_gputrace.h
copyfile services/server/include/pdump_km.h drivers/gpu/drm/img-rogue/pdump_km.h
copyfile services/server/include/pdump_mmu.h drivers/gpu/drm/img-rogue/pdump_mmu.h
copyfile services/server/include/pdump_physmem.h drivers/gpu/drm/img-rogue/pdump_physmem.h
copyfile services/server/include/pdump_symbolicaddr.h drivers/gpu/drm/img-rogue/pdump_symbolicaddr.h
copyfile services/server/include/physmem.h drivers/gpu/drm/img-rogue/physmem.h
copyfile services/server/include/physmem_dlm.h drivers/gpu/drm/img-rogue/physmem_dlm.h
copyfile services/server/include/physmem_dmabuf.h drivers/gpu/drm/img-rogue/physmem_dmabuf.h
copyfile services/server/include/physmem_extmem.h drivers/gpu/drm/img-rogue/physmem_extmem.h
copyfile services/server/include/physmem_hostmem.h drivers/gpu/drm/img-rogue/physmem_hostmem.h
copyfile services/server/include/physmem_ima.h drivers/gpu/drm/img-rogue/physmem_ima.h
copyfile services/server/include/physmem_lma.h drivers/gpu/drm/img-rogue/physmem_lma.h
copyfile services/server/include/physmem_osmem.h drivers/gpu/drm/img-rogue/physmem_osmem.h
copyfile services/server/include/physmem_ramem.h drivers/gpu/drm/img-rogue/physmem_ramem.h
copyfile services/server/include/pmr.h drivers/gpu/drm/img-rogue/pmr.h
copyfile services/server/include/pmr_impl.h drivers/gpu/drm/img-rogue/pmr_impl.h
copyfile services/server/include/pmr_os.h drivers/gpu/drm/img-rogue/pmr_os.h
copyfile services/server/include/power.h drivers/gpu/drm/img-rogue/power.h
copyfile services/server/include/process_stats.h drivers/gpu/drm/img-rogue/process_stats.h
copyfile services/server/include/pvr_notifier.h drivers/gpu/drm/img-rogue/pvr_notifier.h
copyfile services/server/include/pvrsrv.h drivers/gpu/drm/img-rogue/pvrsrv.h
copyfile services/server/include/pvrsrv_apphint.h drivers/gpu/drm/img-rogue/pvrsrv_apphint.h
copyfile services/server/include/pvrsrv_bridge_init.h drivers/gpu/drm/img-rogue/pvrsrv_bridge_init.h
copyfile services/server/include/pvrsrv_cleanup.h drivers/gpu/drm/img-rogue/pvrsrv_cleanup.h
copyfile services/server/include/pvrsrv_device.h drivers/gpu/drm/img-rogue/pvrsrv_device.h
copyfile services/server/include/pvrsrv_pool.h drivers/gpu/drm/img-rogue/pvrsrv_pool.h
copyfile services/server/include/pvrsrv_sync_server.h drivers/gpu/drm/img-rogue/pvrsrv_sync_server.h
copyfile services/server/include/rgx_firmware_boot.h drivers/gpu/drm/img-rogue/rgx_firmware_boot.h
copyfile services/server/include/ri_server.h drivers/gpu/drm/img-rogue/ri_server.h
copyfile services/server/include/sofunc_pvr.h drivers/gpu/drm/img-rogue/sofunc_pvr.h
copyfile services/server/include/srvcore.h drivers/gpu/drm/img-rogue/srvcore.h
copyfile services/server/include/srvinit.h drivers/gpu/drm/img-rogue/srvinit.h
copyfile services/server/include/srvkm.h drivers/gpu/drm/img-rogue/srvkm.h
copyfile services/server/include/sync_checkpoint.h drivers/gpu/drm/img-rogue/sync_checkpoint.h
copyfile services/server/include/sync_checkpoint_init.h drivers/gpu/drm/img-rogue/sync_checkpoint_init.h
copyfile services/server/include/sync_fallback_server.h drivers/gpu/drm/img-rogue/sync_fallback_server.h
copyfile services/server/include/sync_server.h drivers/gpu/drm/img-rogue/sync_server.h
copyfile services/server/include/tlintern.h drivers/gpu/drm/img-rogue/tlintern.h
copyfile services/server/include/tlserver.h drivers/gpu/drm/img-rogue/tlserver.h
copyfile services/server/include/tlstream.h drivers/gpu/drm/img-rogue/tlstream.h
copyfile services/server/include/vmm_impl.h drivers/gpu/drm/img-rogue/vmm_impl.h
copyfile services/server/include/vmm_pvz_client.h drivers/gpu/drm/img-rogue/vmm_pvz_client.h
copyfile services/server/include/vmm_pvz_server.h drivers/gpu/drm/img-rogue/vmm_pvz_server.h
copyfile services/server/include/vz_vm.h drivers/gpu/drm/img-rogue/vz_vm.h
copyfile services/server/include/vz_vmm_pvz.h drivers/gpu/drm/img-rogue/vz_vmm_pvz.h
copyfile services/shared/common/uniq_key_splay_tree.h drivers/gpu/drm/img-rogue/uniq_key_splay_tree.h
copyfile services/shared/devices/rogue/rgx_hwperf_table.h drivers/gpu/drm/img-rogue/rgx_hwperf_table.h
copyfile services/shared/include/allocmem.h drivers/gpu/drm/img-rogue/allocmem.h
copyfile services/shared/include/device_connection.h drivers/gpu/drm/img-rogue/device_connection.h
copyfile services/shared/include/devicemem.h drivers/gpu/drm/img-rogue/devicemem.h
copyfile services/shared/include/devicemem_pdump.h drivers/gpu/drm/img-rogue/devicemem_pdump.h
copyfile services/shared/include/devicemem_utils.h drivers/gpu/drm/img-rogue/devicemem_utils.h
copyfile services/shared/include/hash.h drivers/gpu/drm/img-rogue/hash.h
copyfile services/shared/include/htbuffer.h drivers/gpu/drm/img-rogue/htbuffer.h
copyfile services/shared/include/lock.h drivers/gpu/drm/img-rogue/lock.h
copyfile services/shared/include/osmmap.h drivers/gpu/drm/img-rogue/osmmap.h
copyfile services/shared/include/proc_stats.h drivers/gpu/drm/img-rogue/proc_stats.h
copyfile services/shared/include/ra.h drivers/gpu/drm/img-rogue/ra.h
copyfile services/shared/include/sync.h drivers/gpu/drm/img-rogue/sync.h
copyfile services/shared/include/sync_internal.h drivers/gpu/drm/img-rogue/sync_internal.h
copyfile services/shared/include/tlclient.h drivers/gpu/drm/img-rogue/tlclient.h
copyfile services/system/include/interrupt_support.h drivers/gpu/drm/img-rogue/interrupt_support.h
copyfile services/system/include/pci_support.h drivers/gpu/drm/img-rogue/pci_support.h
copyfile services/system/include/syscommon.h drivers/gpu/drm/img-rogue/syscommon.h
copyfile services/system/include/sysvalidation.h drivers/gpu/drm/img-rogue/sysvalidation.h
copyfile services/system/rogue/include/dma_support.h drivers/gpu/drm/img-rogue/dma_support.h
copyfile services/system/rogue/rgx_linux_tc/sysinfo.h drivers/gpu/drm/img-rogue/apollo/sysinfo.h
copyfile copy-to-kernel-tc/pvrsrvkm.mk drivers/gpu/drm/img-rogue/pvrsrvkm.mk
copyfile copy-to-kernel-tc/drm_pdp.mk drivers/gpu/drm/img-rogue/pdp/drm_pdp.mk
copyfile copy-to-kernel-tc/apollo.mk drivers/gpu/drm/img-rogue/apollo/apollo.mk
copyfile copy-to-kernel-tc/config_kernel.mk drivers/gpu/drm/img-rogue/config_kernel.mk
copyfile copy-to-kernel-tc/config_kernel.h drivers/gpu/drm/img-rogue/config_kernel.h
