# Makefile for the Linux edp driver
# 14 Feb 2017, zhengxiaobin, <mailto:zhengxiaobin@allwinnertech.com>
#
obj-$(CONFIG_EDP_DISP2_SUNXI) += edp.o
#edp-y := drv_edp.o de_edp.o de_edp_core.o de_edp_hal.o
edp-y := drv_edp.o de_edp_hal.o de_edp_core.o de_edp.o drv_edp_common.o
