// SPDX-License-Identifier: GPL-2.0+
#ifndef MPAM_ARCH_INTERNAL_H
#define MPAM_ARCH_INTERNAL_H

#define ID_AA64PFR0_MPAM    BIT(40)

#define MPAMF_IDR        0x0000
#define MPAMF_CPOR_IDR   0x0030
#define MPAMF_CCAP_IDR   0x0038
#define MPAMF_ECR        0x00F0

#define MPAMCFG_PART_SEL 0x0100
#define MPAMCFG_CMAX     0x0108
#define MPAMCFG_CPBM_n   0x1000

/* Sysregs */

/* MPAM0_EL1 */
#define MPAM0_EL1_PARTID_I GENMASK(15, 0)
#define MPAM0_EL1_PARTID_D GENMASK(31, 16)

/* MPAM1_EL1 */
#define MPAM1_EL1_PARTID_I GENMASK(15, 0)
#define MPAM1_EL1_PARTID_D GENMASK(31, 16)
#define MPAM1_EL1_MPAMEN   BIT(63)

/* MPAMIDR_EL1 */
#define MPAMIDR_EL1_PARTID_MAX GENMASK(15, 0)

/* MSC MMRs */

/* MPAMF_IDR */
#define MPAMF_IDR_PARTID_MAX    GENMASK(15, 0)
#define MPAMF_IDR_HAS_CCAP_PART BIT(24)
#define MPAMF_IDR_HAS_CPOR_PART BIT(25)
#define MPAMF_IDR_HAS_PRI_PART  BIT(27)
#define MPAMF_IDR_HAS_RIS       GENMASK(32, 31)

/* MPAMF_CPOR_IDR */
#define MPAMF_CPOR_IDR_CPBM_WD GENMASK(15, 0)

/* MPMAMF_CCAP_IDR */
#define MPAMF_CCAP_IDR_CMAX_WD GENMASK(5, 0)

/* MPAMF_ECR */
#define MPAMF_ECR_INTEN BIT(0)

/* MPAMCFG_PART_SEL */
#define MPAMCFG_PART_SEL_PARTID_SEL GENMASK(15, 0)
#define MPAMCFG_PART_SEL_RIS        GENMASK(27, 24)

#define MPAMCFG_CMAX_CMAX GENMASK(15, 0)

#endif