# SPDX-License-Identifier: GPL-2.0-or-later
# Makefile for the video capture/playback device drivers.
# Copyright 2010 Steven King <sfking@fdwdc.com>
#Copyright(c) 2022-2027 Allwinnertech Co., Ltd
# Each configuration option enables a list of files.
obj-$(CONFIG_CSI_VIN)           += actuator.o

obj-$(CONFIG_ACTUATOR_AD5820)   += ad5820_act.o
obj-$(CONFIG_ACTUATOR_DW9714)   += dw9714_act.o
obj-$(CONFIG_ACTUATOR_FP5510)   += fp5510_act.o
obj-$(CONFIG_ACTUATOR_OV8825)   += ov8825_act.o
obj-$(CONFIG_ACTUATOR_AN41908A)   += an41908a_act.o
obj-$(CONFIG_ACTUATOR_AD5823)   += ad5823_act.o
obj-$(CONFIG_ACTUATOR_CN3927)   += cn3927_act.o
