# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_PHY_CIX_USBDP) += phy-cix-usbdp.o
obj-$(CONFIG_PHY_CIX_USB2) += phy-cix-usb2.o
obj-$(CONFIG_PHY_CIX_USB3) += phy-cix-usb3.o
obj-$(CONFIG_PHY_CIX_PCIE) += phy-cix-pcie.o
