# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the ir-rx drivers.
#

ccflags-y += -I $(srctree)/drivers/media/rc
obj-$(CONFIG_AW_IR_RX) += sunxi-ir-rx.o
obj-$(CONFIG_AW_IR_GPIO_RX) += sunxi-gpio-ir-recv.o
