# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_SUNXI_SRAM) +=	sunxi_sram.o
obj-$(CONFIG_GPU_PM_DOMAINS) += gpu_domain.o
obj-$(CONFIG_SUNXI_SID) +=        sunxi-sid.o
obj-$(CONFIG_SUNXI_DUMP) +=       sunxi-dump.o
