ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/platform
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/platform/logger
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/common
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/isp

obj-y += isp_hw_ops.o
obj-y += isp_hw_utils.o
