# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel mixer device drivers.
#
#

tcon_dir = sunxi_device/hardware/lowlevel_tcon
ccflags-y += -I$(srctree)/$(obj)/$(cur_dir)/

tcon_obj += $(tcon_dir)/tcon_tv_reg.o $(tcon_dir)/tcon_top.o
