#
# Makefile for the Goodix gt9xx_secondary touchscreen driver.
#
#subdir-ccflags-y += -DDEBUG
obj-$(CONFIG_TOUCHSCREEN_GT9XX_SECONDARY)		+= gt9xx_secondary.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_SECONDARY_UPDATE)	+= gt9xx_secondary_update.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_SECONDARY_TOOL)		+= goodix_secondary_tool.o
