#
# Makefile for the linux kernel.
#

obj-y=arisc.o arisc_dram.o arisc-notifier.o arisc-sysfs.o
obj-y += hwmsgbox/
obj-y += hwspinlock/
obj-y += interfaces/
obj-y += message_manager/
obj-y += binary/
