# SPDX-License-Identifier: GPL-2.0
# CIX clocks

obj-$(CONFIG_CLK_SKY1_AUDSS) += clk-sky1-audss.o
obj-$(CONFIG_CIX_CLK_DEBUG) += cix-clk-debug.o

obj-$(CONFIG_CIX_ACPI_CLK) += acpi_clk.o
obj-$(CONFIG_COMMON_CLK_CIX) += clk.o
