
obj-$(CONFIG_TE_SST) := te_sec_storage.o
te_sec_storage-y := sst_storage.o
te_sec_storage-y += sst_dev.o
te_sec_storage-y += sst_communicate.o
te_sec_storage-y += sst_core.o
te_sec_storage-y += sst_store.o
te_sec_storage-y += sst_debug.o
