obj-$(CONFIG_AW_AXP) += axp-core.o
obj-$(CONFIG_AW_AXP) += axp-sysfs.o
obj-$(CONFIG_AW_AXP) += axp-virtual.o
obj-$(CONFIG_AW_AXP) += axp-powerkey.o
obj-$(CONFIG_AW_AXP) += axp-charger.o
obj-$(CONFIG_AW_AXP) += axp-gpio.o
obj-$(CONFIG_AW_AXP) += axp-regulator.o
obj-$(CONFIG_AW_AXP) += nmi/sunxi-nmi.o

#AXP22X
obj-$(CONFIG_AW_AXP22X) += axp22x/axp22x.o
obj-$(CONFIG_AW_AXP22X) += axp22x/axp22x-regulator.o
obj-$(CONFIG_AW_AXP22X) += axp22x/axp22x-charger.o
obj-$(CONFIG_AW_AXP22X) += axp22x/axp22x-gpio.o
obj-$(CONFIG_AW_AXP22X) += axp22x/axp22x-powerkey.o
obj-$(CONFIG_AW_AXP22X) += axp22x/axp22x-virtual.o

#AXP259
obj-$(CONFIG_AW_AXP259) += axp259/axp259.o
obj-$(CONFIG_AW_AXP259) += axp259/axp259-charger.o
obj-$(CONFIG_AW_AXP259) += axp259/axp259-gpio.o
obj-$(CONFIG_AW_AXP259) += axp259/axp259-powerkey.o

#AXP80X
obj-$(CONFIG_AW_AXP80X) += axp80x/axp80x.o
obj-$(CONFIG_AW_AXP80X) += axp80x/axp80x-regulator.o
obj-$(CONFIG_AW_AXP80X) += axp80x/axp80x-gpio.o
obj-$(CONFIG_AW_AXP80X) += axp80x/axp80x-powerkey.o
obj-$(CONFIG_AW_AXP80X) += axp80x/axp80x-virtual.o

#AXP803
obj-$(CONFIG_AW_AXP803) += axp803/axp803.o
obj-$(CONFIG_AW_AXP803) += axp803/axp803-regulator.o
obj-$(CONFIG_AW_AXP803) += axp803/axp803-charger.o
obj-$(CONFIG_AW_AXP803) += axp803/axp803-gpio.o
obj-$(CONFIG_AW_AXP803) += axp803/axp803-powerkey.o
obj-$(CONFIG_AW_AXP803) += axp803/axp803-virtual.o

#PMU1736
obj-$(CONFIG_AW_PMU1736) += pmu1736/pmu1736.o
obj-$(CONFIG_AW_PMU1736) += pmu1736/pmu1736-regu.o
obj-$(CONFIG_AW_PMU1736) += pmu1736/pmu1736-gpio.o
obj-$(CONFIG_AW_PMU1736) += pmu1736/pmu1736-powerkey.o
obj-$(CONFIG_AW_PMU1736) += pmu1736/virtual_pmu1736.o
obj-$(CONFIG_AW_PMU1736) += pmu1736/virtual_pmu1736_dev.o

#BMU1760
obj-$(CONFIG_AW_BMU1760) += bmu1760/bmu1760.o
obj-$(CONFIG_AW_BMU1760) += bmu1760/bmu1760-charger.o
obj-$(CONFIG_AW_BMU1760) += bmu1760/bmu1760-powerkey.o
