NOSTDINC_FLAGS := -I$(srctree)/drivers/net/wireless/xr829/include/

obj-$(CONFIG_XR829_WLAN) += umac/
obj-$(CONFIG_XR829_WLAN) += wlan/

clean-files += Module.symvers Module.markers modules modules.order
