# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_CRYPTO_DEV_ROCKCHIP) += rk_crypto.o
rk_crypto-objs := rk3288_crypto.o \
		  rk3288_crypto_skcipher.o \
		  rk3288_crypto_ahash.o

obj-$(CONFIG_CRYPTO_DEV_ROCKCHIP2) += rk_crypto2.o
rk_crypto2-objs := rk3588_crypto.o \
		  rk3588_crypto_skcipher.o \
		  rk3588_crypto_ahash.o
