/******************************************************************************
 *
 * Copyright(c) 2016 - 2017 Realtek Corporation. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 ******************************************************************************/

#ifndef _HALMAC_TX_DESC_BUFFER_CHIP_H_
#define _HALMAC_TX_DESC_BUFFER_CHIP_H_
#if (HALMAC_8814B_SUPPORT)

/*TXDESC_WORD0*/

#define SET_TX_DESC_BUFFER_RDG_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_RDG_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_RDG_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_RDG_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_BCNPKT_TSF_CTRL_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_BCNPKT_TSF_CTRL(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_BCNPKT_TSF_CTRL_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_BCNPKT_TSF_CTRL(__pTxDesc)
#define SET_TX_DESC_BUFFER_AGG_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_AGG_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_AGG_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_AGG_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_PKT_OFFSET_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_PKT_OFFSET(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_PKT_OFFSET_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_PKT_OFFSET(__pTxDesc)
#define SET_TX_DESC_BUFFER_OFFSET_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_OFFSET(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_OFFSET_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_OFFSET(__pTxDesc)
#define SET_TX_DESC_BUFFER_TXPKTSIZE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_TXPKTSIZE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_TXPKTSIZE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_TXPKTSIZE(__pTxDesc)

/*TXDESC_WORD1*/

#define SET_TX_DESC_BUFFER_USERATE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_USERATE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_USERATE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_USERATE(__pTxDesc)
#define SET_TX_DESC_BUFFER_AMSDU_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_AMSDU(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_AMSDU_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_AMSDU(__pTxDesc)
#define SET_TX_DESC_BUFFER_EN_HWSEQ_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_EN_HWSEQ(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_EN_HWSEQ_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_EN_HWSEQ(__pTxDesc)
#define SET_TX_DESC_BUFFER_EN_HWEXSEQ_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_EN_HWEXSEQ(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_EN_HWEXSEQ_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_EN_HWEXSEQ(__pTxDesc)
#define SET_TX_DESC_BUFFER_SW_SEQ_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_SW_SEQ(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_SW_SEQ_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_SW_SEQ(__pTxDesc)
#define SET_TX_DESC_BUFFER_DROP_ID_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_DROP_ID(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_DROP_ID_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_DROP_ID(__pTxDesc)
#define SET_TX_DESC_BUFFER_MOREDATA_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_MOREDATA(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_MOREDATA_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_MOREDATA(__pTxDesc)
#define SET_TX_DESC_BUFFER_QSEL_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_QSEL(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_QSEL_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_QSEL(__pTxDesc)
#define SET_TX_DESC_BUFFER_MACID_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_MACID(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_MACID_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_MACID(__pTxDesc)

/*TXDESC_WORD2*/

#define SET_TX_DESC_BUFFER_CHK_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_CHK_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_CHK_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_CHK_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_DISQSELSEQ_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_DISQSELSEQ(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_DISQSELSEQ_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_DISQSELSEQ(__pTxDesc)
#define SET_TX_DESC_BUFFER_SND_PKT_SEL_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_SND_PKT_SEL(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_SND_PKT_SEL_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_SND_PKT_SEL(__pTxDesc)
#define SET_TX_DESC_BUFFER_DMA_PRI_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_DMA_PRI(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_DMA_PRI_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_DMA_PRI(__pTxDesc)
#define SET_TX_DESC_BUFFER_MAX_AMSDU_MODE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_MAX_AMSDU_MODE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_MAX_AMSDU_MODE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_MAX_AMSDU_MODE(__pTxDesc)
#define SET_TX_DESC_BUFFER_DMA_TXAGG_NUM_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_DMA_TXAGG_NUM(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_DMA_TXAGG_NUM_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_DMA_TXAGG_NUM(__pTxDesc)
#define SET_TX_DESC_BUFFER_TXDESC_CHECKSUM_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_TXDESC_CHECKSUM(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_TXDESC_CHECKSUM_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_TXDESC_CHECKSUM(__pTxDesc)

/*TXDESC_WORD3*/

#define SET_TX_DESC_BUFFER_OFFLOAD_SIZE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_OFFLOAD_SIZE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_OFFLOAD_SIZE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_OFFLOAD_SIZE(__pTxDesc)
#define SET_TX_DESC_BUFFER_CHANNEL_DMA_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_CHANNEL_DMA(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_CHANNEL_DMA_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_CHANNEL_DMA(__pTxDesc)
#define SET_TX_DESC_BUFFER_MBSSID_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_MBSSID(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_MBSSID_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_MBSSID(__pTxDesc)
#define SET_TX_DESC_BUFFER_BK_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_BK(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_BK_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_BK(__pTxDesc)
#define SET_TX_DESC_BUFFER_WHEADER_LEN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_WHEADER_LEN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_WHEADER_LEN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_WHEADER_LEN(__pTxDesc)

/*TXDESC_WORD4*/

#define SET_TX_DESC_BUFFER_TRY_RATE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_TRY_RATE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_TRY_RATE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_TRY_RATE(__pTxDesc)
#define SET_TX_DESC_BUFFER_DATA_BW_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_DATA_BW(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_DATA_BW_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_DATA_BW(__pTxDesc)
#define SET_TX_DESC_BUFFER_DATA_SHORT_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_DATA_SHORT(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_DATA_SHORT_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_DATA_SHORT(__pTxDesc)
#define SET_TX_DESC_BUFFER_DATARATE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_DATARATE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_DATARATE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_DATARATE(__pTxDesc)
#define SET_TX_DESC_BUFFER_TXBF_PATH_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_TXBF_PATH(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_TXBF_PATH_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_TXBF_PATH(__pTxDesc)
#define SET_TX_DESC_BUFFER_GROUP_BIT_IE_OFFSET_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_GROUP_BIT_IE_OFFSET(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_GROUP_BIT_IE_OFFSET_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_GROUP_BIT_IE_OFFSET(__pTxDesc)

/*TXDESC_WORD5*/

#define SET_TX_DESC_BUFFER_RTY_LMT_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_RTY_LMT_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_RTY_LMT_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_RTY_LMT_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_HW_RTS_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_HW_RTS_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_HW_RTS_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_HW_RTS_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_RTS_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_RTS_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_RTS_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_RTS_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_CTS2SELF_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_CTS2SELF(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_CTS2SELF_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_CTS2SELF(__pTxDesc)
#define SET_TX_DESC_BUFFER_TAILPAGE_H_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_TAILPAGE_H(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_TAILPAGE_H_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_TAILPAGE_H(__pTxDesc)
#define SET_TX_DESC_BUFFER_TAILPAGE_L_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_TAILPAGE_L(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_TAILPAGE_L_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_TAILPAGE_L(__pTxDesc)
#define SET_TX_DESC_BUFFER_NAVUSEHDR_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_NAVUSEHDR(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_NAVUSEHDR_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_NAVUSEHDR(__pTxDesc)
#define SET_TX_DESC_BUFFER_BMC_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_BMC(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_BMC_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_BMC(__pTxDesc)
#define SET_TX_DESC_BUFFER_RTS_DATA_RTY_LMT_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_RTS_DATA_RTY_LMT(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_RTS_DATA_RTY_LMT_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_RTS_DATA_RTY_LMT(__pTxDesc)
#define SET_TX_DESC_BUFFER_HW_AES_IV_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_HW_AES_IV(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_HW_AES_IV_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_HW_AES_IV(__pTxDesc)
#define SET_TX_DESC_BUFFER_BT_NULL_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_BT_NULL(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_BT_NULL_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_BT_NULL(__pTxDesc)
#define SET_TX_DESC_BUFFER_EN_DESC_ID_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_EN_DESC_ID(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_EN_DESC_ID_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_EN_DESC_ID(__pTxDesc)
#define SET_TX_DESC_BUFFER_SECTYPE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_SECTYPE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_SECTYPE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_SECTYPE(__pTxDesc)

/*TXDESC_WORD6*/

#define SET_TX_DESC_BUFFER_MULTIPLE_PORT_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_MULTIPLE_PORT(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_MULTIPLE_PORT_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_MULTIPLE_PORT(__pTxDesc)
#define SET_TX_DESC_BUFFER_POLLUTED_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_POLLUTED(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_POLLUTED_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_POLLUTED(__pTxDesc)
#define SET_TX_DESC_BUFFER_NULL_1_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_NULL_1(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_NULL_1_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_NULL_1(__pTxDesc)
#define SET_TX_DESC_BUFFER_NULL_0_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_NULL_0(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_NULL_0_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_NULL_0(__pTxDesc)
#define SET_TX_DESC_BUFFER_TRI_FRAME_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_TRI_FRAME(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_TRI_FRAME_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_TRI_FRAME(__pTxDesc)
#define SET_TX_DESC_BUFFER_SPE_RPT_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_SPE_RPT(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_SPE_RPT_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_SPE_RPT(__pTxDesc)
#define SET_TX_DESC_BUFFER_FTM_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_FTM_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_FTM_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_FTM_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_MU_DATARATE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_MU_DATARATE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_MU_DATARATE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_MU_DATARATE(__pTxDesc)
#define SET_TX_DESC_BUFFER_CCA_RTS_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_CCA_RTS(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_CCA_RTS_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_CCA_RTS(__pTxDesc)
#define SET_TX_DESC_BUFFER_NDPA_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_NDPA(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_NDPA_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_NDPA(__pTxDesc)
#define SET_TX_DESC_BUFFER_TXPWR_OFSET_TYPE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_TXPWR_OFSET_TYPE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_TXPWR_OFSET_TYPE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_TXPWR_OFSET_TYPE(__pTxDesc)
#define SET_TX_DESC_BUFFER_P_AID_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_P_AID(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_P_AID_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_P_AID(__pTxDesc)

/*TXDESC_WORD7*/

#define SET_TX_DESC_BUFFER_SW_DEFINE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_SW_DEFINE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_SW_DEFINE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_SW_DEFINE(__pTxDesc)
#define SET_TX_DESC_BUFFER_CTRL_CNT_VALID_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_CTRL_CNT_VALID(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_CTRL_CNT_VALID_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_CTRL_CNT_VALID(__pTxDesc)
#define SET_TX_DESC_BUFFER_CTRL_CNT_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_CTRL_CNT(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_CTRL_CNT_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_CTRL_CNT(__pTxDesc)
#define SET_TX_DESC_BUFFER_DATA_RTY_LOWEST_RATE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_DATA_RTY_LOWEST_RATE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_DATA_RTY_LOWEST_RATE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_DATA_RTY_LOWEST_RATE(__pTxDesc)

/*TXDESC_WORD8*/

#define SET_TX_DESC_BUFFER_PATH_MAPA_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_PATH_MAPA(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_PATH_MAPA_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_PATH_MAPA(__pTxDesc)
#define SET_TX_DESC_BUFFER_PATH_MAPB_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_PATH_MAPB(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_PATH_MAPB_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_PATH_MAPB(__pTxDesc)
#define SET_TX_DESC_BUFFER_PATH_MAPC_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_PATH_MAPC(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_PATH_MAPC_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_PATH_MAPC(__pTxDesc)
#define SET_TX_DESC_BUFFER_PATH_MAPD_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_PATH_MAPD(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_PATH_MAPD_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_PATH_MAPD(__pTxDesc)
#define SET_TX_DESC_BUFFER_ANTSEL_A_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_ANTSEL_A(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_ANTSEL_A_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_ANTSEL_A(__pTxDesc)
#define SET_TX_DESC_BUFFER_ANTSEL_B_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_ANTSEL_B(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_ANTSEL_B_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_ANTSEL_B(__pTxDesc)
#define SET_TX_DESC_BUFFER_ANTSEL_C_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_ANTSEL_C(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_ANTSEL_C_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_ANTSEL_C(__pTxDesc)
#define SET_TX_DESC_BUFFER_ANTSEL_D_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_ANTSEL_D(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_ANTSEL_D_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_ANTSEL_D(__pTxDesc)
#define SET_TX_DESC_BUFFER_NTX_PATH_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_NTX_PATH_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_NTX_PATH_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_NTX_PATH_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_ANTLSEL_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_ANTLSEL_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_ANTLSEL_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_ANTLSEL_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_AMPDU_DENSITY_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_AMPDU_DENSITY(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_AMPDU_DENSITY_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_AMPDU_DENSITY(__pTxDesc)

/*TXDESC_WORD9*/

#define SET_TX_DESC_BUFFER_VCS_STBC_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_VCS_STBC(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_VCS_STBC_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_VCS_STBC(__pTxDesc)
#define SET_TX_DESC_BUFFER_DATA_STBC_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_DATA_STBC(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_DATA_STBC_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_DATA_STBC(__pTxDesc)
#define SET_TX_DESC_BUFFER_RTS_RTY_LOWEST_RATE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_RTS_RTY_LOWEST_RATE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_RTS_RTY_LOWEST_RATE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_RTS_RTY_LOWEST_RATE(__pTxDesc)
#define SET_TX_DESC_BUFFER_SIGNALING_TA_PKT_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_SIGNALING_TA_PKT_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_SIGNALING_TA_PKT_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_SIGNALING_TA_PKT_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_MHR_CP_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_MHR_CP(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_MHR_CP_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_MHR_CP(__pTxDesc)
#define SET_TX_DESC_BUFFER_SMH_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_SMH_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_SMH_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_SMH_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_RTSRATE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_RTSRATE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_RTSRATE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_RTSRATE(__pTxDesc)
#define SET_TX_DESC_BUFFER_SMH_CAM_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_SMH_CAM(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_SMH_CAM_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_SMH_CAM(__pTxDesc)
#define SET_TX_DESC_BUFFER_ARFR_TABLE_SEL_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_ARFR_TABLE_SEL(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_ARFR_TABLE_SEL_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_ARFR_TABLE_SEL(__pTxDesc)
#define SET_TX_DESC_BUFFER_ARFR_HT_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_ARFR_HT_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_ARFR_HT_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_ARFR_HT_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_ARFR_OFDM_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_ARFR_OFDM_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_ARFR_OFDM_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_ARFR_OFDM_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_ARFR_CCK_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_ARFR_CCK_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_ARFR_CCK_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_ARFR_CCK_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_RTS_SHORT_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_RTS_SHORT(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_RTS_SHORT_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_RTS_SHORT(__pTxDesc)
#define SET_TX_DESC_BUFFER_DISDATAFB_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_DISDATAFB(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_DISDATAFB_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_DISDATAFB(__pTxDesc)
#define SET_TX_DESC_BUFFER_DISRTSFB_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_DISRTSFB(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_DISRTSFB_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_DISRTSFB(__pTxDesc)
#define SET_TX_DESC_BUFFER_EXT_EDCA_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_EXT_EDCA(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_EXT_EDCA_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_EXT_EDCA(__pTxDesc)

/*TXDESC_WORD10*/

#define SET_TX_DESC_BUFFER_AMPDU_MAX_TIME_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_AMPDU_MAX_TIME(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_AMPDU_MAX_TIME_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_AMPDU_MAX_TIME(__pTxDesc)
#define SET_TX_DESC_BUFFER_SPECIAL_CW_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_SPECIAL_CW(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_SPECIAL_CW_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_SPECIAL_CW(__pTxDesc)
#define SET_TX_DESC_BUFFER_RDG_NAV_EXT_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_RDG_NAV_EXT(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_RDG_NAV_EXT_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_RDG_NAV_EXT(__pTxDesc)
#define SET_TX_DESC_BUFFER_RAW_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_RAW(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_RAW_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_RAW(__pTxDesc)
#define SET_TX_DESC_BUFFER_MAX_AGG_NUM_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_MAX_AGG_NUM(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_MAX_AGG_NUM_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_MAX_AGG_NUM(__pTxDesc)
#define SET_TX_DESC_BUFFER_FINAL_DATA_RATE_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_FINAL_DATA_RATE(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_FINAL_DATA_RATE_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_FINAL_DATA_RATE(__pTxDesc)
#define SET_TX_DESC_BUFFER_GF_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_GF(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_GF_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_GF(__pTxDesc)
#define SET_TX_DESC_BUFFER_MOREFRAG_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_MOREFRAG(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_MOREFRAG_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_MOREFRAG(__pTxDesc)
#define SET_TX_DESC_BUFFER_NOACM_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_NOACM(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_NOACM_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_NOACM(__pTxDesc)
#define SET_TX_DESC_BUFFER_HTC_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_HTC(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_HTC_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_HTC(__pTxDesc)
#define SET_TX_DESC_BUFFER_TX_PKT_AFTER_PIFS_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_TX_PKT_AFTER_PIFS(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_TX_PKT_AFTER_PIFS_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_TX_PKT_AFTER_PIFS(__pTxDesc)
#define SET_TX_DESC_BUFFER_USE_MAX_TIME_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_USE_MAX_TIME_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_USE_MAX_TIME_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_USE_MAX_TIME_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_HW_SSN_SEL_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_HW_SSN_SEL(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_HW_SSN_SEL_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_HW_SSN_SEL(__pTxDesc)

/*TXDESC_WORD11*/

#define SET_TX_DESC_BUFFER_ADDR_CAM_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_ADDR_CAM(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_ADDR_CAM_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_ADDR_CAM(__pTxDesc)
#define SET_TX_DESC_BUFFER_SND_TARGET_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_SND_TARGET(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_SND_TARGET_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_SND_TARGET(__pTxDesc)
#define SET_TX_DESC_BUFFER_DATA_LDPC_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_DATA_LDPC(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_DATA_LDPC_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_DATA_LDPC(__pTxDesc)
#define SET_TX_DESC_BUFFER_LSIG_TXOP_EN_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_LSIG_TXOP_EN(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_LSIG_TXOP_EN_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_LSIG_TXOP_EN(__pTxDesc)
#define SET_TX_DESC_BUFFER_G_ID_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_G_ID(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_G_ID_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_G_ID(__pTxDesc)
#define SET_TX_DESC_BUFFER_SIGNALING_TA_PKT_SC_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_SIGNALING_TA_PKT_SC(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_SIGNALING_TA_PKT_SC_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_SIGNALING_TA_PKT_SC(__pTxDesc)
#define SET_TX_DESC_BUFFER_DATA_SC_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_DATA_SC(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_DATA_SC_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_DATA_SC(__pTxDesc)

/*TXDESC_WORD12*/

#define SET_TX_DESC_BUFFER_LEN1_L_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_LEN1_L(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_LEN1_L_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_LEN1_L(__pTxDesc)
#define SET_TX_DESC_BUFFER_LEN0_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_LEN0(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_LEN0_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_LEN0(__pTxDesc)
#define SET_TX_DESC_BUFFER_PKT_NUM_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_PKT_NUM(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_PKT_NUM_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_PKT_NUM(__pTxDesc)

/*TXDESC_WORD13*/

#define SET_TX_DESC_BUFFER_LEN3_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_LEN3(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_LEN3_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_LEN3(__pTxDesc)
#define SET_TX_DESC_BUFFER_LEN2_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_LEN2(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_LEN2_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_LEN2(__pTxDesc)
#define SET_TX_DESC_BUFFER_LEN1_H_8814B(__pTxDesc, __Value)    SET_TX_DESC_BUFFER_LEN1_H(__pTxDesc, __Value)
#define GET_TX_DESC_BUFFER_LEN1_H_8814B(__pTxDesc)    GET_TX_DESC_BUFFER_LEN1_H(__pTxDesc)

#endif


#endif

