ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/platform/logger
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/platform/hdmi
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/common
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/common/isp_hw_if
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/sensor

obj-y += armcb_platform.o
obj-y += bus/
obj-y += logger/
