#
# Makefile for the SPINAND MTD
#

obj-$(CONFIG_AW_MTD_SPINAND) += aw-ubi-spinand.o

aw-ubi-spinand-objs += sunxi-core.o sunxi-debug.o

#obj-$(CONFIG_AW_NFTL_SPINAND) += aw-nftl-spinand.o

#aw-nftl-spinand-objs += sunxi-common.o sunxi-nftl-core.o

obj-$(CONFIG_AW_SPINAND_PHYSICAL_LAYER) += physic/

obj-$(CONFIG_AW_SPINAND_SECURE_STORAGE) += secure-storage.o
