# Android Switch Class Driver
obj-$(CONFIG_ANDROID_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_HEADSET)		+= switch_headset.o
obj-$(CONFIG_ANDROID_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_ANDROID_SWITCH_GPIO_TS3A225)	+= switch_ts3a225.o
obj-$(CONFIG_SOC_SWITCH_GPIO)	+= ac100_switch_gpio.o

