# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel USB device drivers.
#

obj-$(CONFIG_USB_SUNXI_HCI)	+= host/
obj-$(CONFIG_USB_SUNXI_USB)	+= sunxi_usb/
obj-$(CONFIG_USB_SUNXI_DWC3)	+= dwc3/
obj-$(CONFIG_USB_SUNXI_TYPEC)	+= typec/
obj-$(CONFIG_USB_SUNXI_GADGET)	+= gadget/
obj-$(CONFIG_USB_SUNXI_EXTCON)	+= extcon/
obj-$(CONFIG_USB_SUNXI_PHY)	+= phy/

